(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"Holley_DuckCharacter_atlas_1", frames: [[0,0,1281,934]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_1 = function() {
	this.initialize(ss["Holley_DuckCharacter_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.head = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// pupil
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLAAQAAA6gpAoQgoApg6AAQgTAAgSgFQgigJgbgbQgogoAAg6QAAg4AogqQAbgaAigJQASgFATAAQA6AAAoAoQApAqAAA4g");
	this.shape.setTransform(18.3,-14.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AglCGQgigJgagbQgpgoAAg6QAAg4ApgqQAagaAigJQASgFATAAQA6AAAoAoQApAqAAA4QAAA6gpAoQgoApg6AAQgTAAgSgFg");
	this.shape_1.setTransform(18.3,-14.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLAPQAAA6gpAPQgoAQg6AAQg5AAgogQQgpgPAAg6QAAg4ApgeQAogfA5gBQA6gBAoAfQApAgAAA4g");
	this.shape_2.setTransform(18.3,-15.6522);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhhBYQgpgPAAg6QAAg4ApgeQAogfA5gBQA6gBAoAfQApAgAAA4QAAA6gpAPQgoAQg6AAQg5AAgogQg");
	this.shape_3.setTransform(18.3,-15.6522);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLgIQAAA5gvAKQgvAKg2ABQg3ACglgLQglgMAAg5QAAg5AuACQAuACA4gGQA5gFAkAEQAkADAAA5g");
	this.shape_4.setTransform(18.3,-13.2947);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AhlA9QglgMAAg5QAAg5AuACQAuACA4gGQA5gFAkAEQAkADAAA5QAAA5gvAKQgvAKg2ABIgPABQgtAAgggKg");
	this.shape_5.setTransform(18.3,-13.2947);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFCE00").s().p("AgyDiIgGgBIgHgDQgJgHgHgIQgIgJgEgLIgGgRIgEgUIgEgTIgDgUIgGgCIgFgCIgFgEIgEgEIgEgEIgDgFIgDgEIgKgMIgKgLIgJgLIgJgLIgHgKIgEgFIgLgKIgKgLIgJgIIgJgJIgJgLIgEgFIgDgHIgDgGIgCgGIgCgGIAAgGIABgFIABgGIACgFIADgFIADgEIADgEIAEgDIAEgEIAFgCIAFgCIAFAAIAFgBIAGAAIAFABIAFACIAFACIAEAEIAFADIAEAFIAEADIADAFIADAEIADAFIAEAFIAFAFIAFAFIADAFIAEAEIADAFIAEAEIACADQADAAgBgNIAAgXIAAgPIAAgPIAAgNIABgGIADgFIACgGIAEgEIAEgEIAEgDIAFgDIgCgHIgEgNIgCgMIgBgOIABgEIADgKIACgFIACgEIAEgFIAEgDIAEgDIAFgDIAFgBIAFgBIAFAAIAGABIAFAAIAFACIAEACIAFADIAEADIAEAEIAEAEIAEAEIADgFIADgEIAEgEIAFgDIAEgDIAGgCIAFgBIAFAAIAFAAIAFABIAFACIAEADIAFACIAEADIADAFIADADIADAGIADALIAEAOIACAMIABAIIABAGIAAAHIADgCIAEgCIAFgBIAFgBIAGgBIAFABIAFABIAFABIAFACIAFADIAFAFIAFADIAEAFIAFAEIAEAFIAFAFIAFAFIAFgFIAEgEIAFgFIAFgEIAGgDIAFgEIAGgCIAFgCIAGgBIAGAAIAFAAIAGABIAFACIAFACIAFAEIAEADIAEAEQAJAOAFAQIAJAgQAFARACAQQADAQAAAQIAAAjIgBAFIgBAFIgBAFIgCAFIgDAEIgCAFIgDADIgEAEIgFADIgEABIgEACIABAEIADAGIACAHIACAGIABAHIACAGIADAGIADAFIADAGIADAHIADAFIACAGIABAGIABAFIgBAHIgBAGIgDAFIgDAGIgEAEIgEAEIgFADIgEACIgFACIgFABIgFABIgGgBIgFgBIgFgCIgEgCIgFgDIgEgEIgDgDIgCgDIgEgGIgEgFIgDgGIAAgBIABADIgDgFIgDgFIgDgFIgCgFIgCgGIgBgFIgCgGIgEAEIgFAEIgFADIgGAEIgGADIgFACIgGACIgGAEIgFACIAAABIgEAFIgEAFIgFAEIgFAEIgGADIgHACIgGACIgGABIgGACIgGADIgGACIgHABIgHABIgHAAIgHADIgIACIgGADIAAAAIgGAFIgFAEIgGAEIgGAEIgGACIgGABIgHAAIgHAAg");
	this.shape_6.setTransform(13.025,-15.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLgDQAHA4gzAkQgzAkg1gQQg3gQglgYQglgYAAg0QgBg2AlgXQAkgXA5gFQA3gFArAcQAqAdAIA5g");
	this.shape_7.setTransform(18.3477,-13.738);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgJBtQg3gQglgYQglgYAAg0QgBg2AlgXQAkgXA5gFQA3gFArAcQAqAdAIA5QAHA4gzAkQgjAZglAAQgRAAgPgFg");
	this.shape_8.setTransform(18.3477,-13.738);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLgWQAKBZguAtQguAtg9gCQg+gDglgxQglgxAAg1QAAg1AkgxQAkgxA5gDQA4gEAqAXQAqAXAKBZg");
	this.shape_9.setTransform(18.5161,-14.6059);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgECbQg+gDglgxQglgxAAg1QAAg1AkgxQAkgxA5gDQA4gEAqAXQAqAXAKBZQAKBZguAtQgrArg6AAIgGAAg");
	this.shape_10.setTransform(18.5161,-14.6059);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},6).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},4).to({state:[{t:this.shape_8},{t:this.shape_7}]},1).to({state:[{t:this.shape_10},{t:this.shape_9}]},1).wait(9));

	// eyes
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("AClAAQAABmgxBHQgvBIhFAAQgPAAgOgEQgxgMgmg4QgwhHAAhmQAAhkAwhIQAmg4AxgMQAOgEAPAAQBFAAAvBIQAxBIAABkg");
	this.shape_11.setTransform(17.5,-16.45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgdDxQgxgMgmg4QgwhHAAhmQAAhkAwhJQAmg3AxgMQAOgEAPAAQBFAAAwBHQAwBJAABkQAABmgwBHQgwBIhFAAQgPAAgOgEg");
	this.shape_12.setTransform(17.5,-16.45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("AClgTQAABlgwAyQgwAzhFACQhEADgwg1Qgwg1AAhlQAAhlA1gjQA1giBEAFQBFAGArAdQArAdAABlg");
	this.shape_13.setTransform(17.5,-14.4809);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ah0CHQgwg1AAhlQAAhlA1gjQA1giBEAFQBFAGArAdQArAdAABlQAABlgwAyQgwAzhFACIgFAAQhBAAgugyg");
	this.shape_14.setTransform(17.5,-14.4809);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACegHQASBTgsAPQgrAQhEACQhEADg1gSQg1gSgJhUQgIhVBugKQBtgKAbAJQAbAKATABQATACARBUg");
	this.shape_15.setTransform(16.4349,-13.8659);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhkBeQg1gSgJhUQgIhVBugKQBtgKAbAJQAbAKATABQATACARBUQASBTgsAPQgrAQhEACIgRAAQg6AAgugPg");
	this.shape_16.setTransform(16.4349,-13.8659);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACcAFQAGBVgkA3QgkA2g1APQg1AOhMhFQhMhFAPieQAOigCCAOQCBAOASAuQASAugDAPQgDAOAGBUg");
	this.shape_17.setTransform(17.8393,-15.3066);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhcCfQhMhFAPieQAOigCCAOQCBAOASAuQASAugDAPQgDAOAGBUQAGBVgkA3QgkA2g1APQgKACgKAAQguAAg/g5g");
	this.shape_18.setTransform(17.8393,-15.3066);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACoAPQAGBVgaBVQgaBWhZANQhYAMhAhiQhAhiAUjAQAUjBB+ABQB+ABAeBdQAdBcgDAPQgDAOAGBUg");
	this.shape_19.setTransform(16.6125,-16.3001);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ah3DGQhAhiAUjAQAUjBB+ABQB+ABAeBcQAdBdgDAPQgDAOAGBUQAGBVgaBVQgaBWhZANIgVABQhLAAg4hXg");
	this.shape_20.setTransform(16.6125,-16.3001);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11}]}).to({state:[{t:this.shape_14},{t:this.shape_13}]},6).to({state:[{t:this.shape_16},{t:this.shape_15}]},2).to({state:[{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_16},{t:this.shape_15}]},4).to({state:[{t:this.shape_18},{t:this.shape_17}]},1).to({state:[{t:this.shape_20},{t:this.shape_19}]},1).wait(9));

	// head
	this.instance = new lib.CachedBmp_1();
	this.instance.setTransform(-514.05,-92.25,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-514,-92.2,640.5,467);


(lib.walking = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {walking:0,standing:25};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_24 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(24).call(this.frame_24).wait(5).call(this.frame_29).wait(1));

	// head
	this.instance = new lib.head();
	this.instance.setTransform(-112.05,86.7,0.5973,0.627,0,0,0,-193.8,141.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2).to({y:93.1},0).wait(2).to({y:103.6},0).wait(2).to({y:113.7},0).wait(2).to({y:86.7},0).wait(2).to({y:93.1},0).wait(2).to({y:103.6},0).wait(2).to({y:113.7},0).wait(2).to({y:86.7},0).wait(2).to({y:93.1},0).wait(2).to({y:103.6},0).wait(2).to({y:113.7},0).wait(2).to({y:86.7},0).wait(2).to({y:93.1},0).wait(2).to({y:86.7},0).wait(2));

	// legs
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF6600").s().p("ApFHqIgMAAIgGAAIgFgBIgFgBIgFgCIgFgCIgEgDIgCgBIgCABIgFgBIgGgBIgFgCIgEgCIgFgCIgEgEIgDgEIgDgFIgGgMIgFgOIgFgNIgCgIIgCgIIgCgHIgCgHIgCgGIgDgGIgDgFIgDgGIgCgGIgCgHIgDgFIgCgEIgCgFIgCgFIgBgFIAAgEIgBgFIgBgEIgCgFIgCgHIgCgFIgBgHIgBgGIgBgGIAAgGIAAgHIAAgGIAAgGIAAgGIgDgFIgCgFIgBgGIgCgEIAAgBIgEgFIgEgEIgEgFIgEgEIgEgGIgCgHIgDgGIgCgGIgBgGIgDgGIgDgHIgCgHIgBgFIAAgGIgBgBIgCgGIgCgFIgCgFIgBgIIgBgHIgBgFIAAgGIAAgFIABgFIACgGIACgEIADgFIAEgEIAEgCIAEgEIAFgCIADgBIABgIQACgIADgIIAIgRIAJgSQAFgIAGgGIAFgGQADgKAGgKQAEgJAGgGIALgNIANgNIAHgHQgGgHgEgHIgHgTIgFgMQgDgIgFgGIgHgKIgDgGIgCgHIgCgFIgBgHIgDgGIgCgFIgCgFIgBgEIgDgFIgCgDIgCgFIgBgGIgBgHIgBgHIAAgGIgCgGIgCgHIgCgGIgBgGIgBgIIgBgHIAAgIIgBgIIgEgUIgEgaIgDgUIgEgVQgCgOAAgPIABgFIABgFIABgFIADgFIADgEIADgEIAEgDIAEgDIAFgDIAFgBIAFgBIAFAAIACAAIABgBIAFgDIAEgDIAFgCIAFAAIAdgBIAfAAIAWAAIAXAAIATABIAMABIAGABIAFADIAFAEIAFAAIAGgBIAFgBIAFABIAFABIAFABIAFACIAEADIAEADIAEAFIADADIACAGIACAEIABAGIAAACIABADIABAFIABAFIAAAHIAAAIIAAAHIABAFIACAGIACAGIABAFIADAHIADAIIACAGIACAHIAEAGIADAFIAEAEIACAGIACAFIACAGIACAGIAEAFIAEAGIADAFIAEAFIAFAEIAEAEIAEAFIADAFIADAFIADAFIADAFIAEAGIAFAGIAFADIAEAEIAFAFIAFAEIAEAGIAFAGIADAFIADAFIADAGIACAFIACAHIADAFIADAFIACAGIACAHIABAFIAAAGIAAAEIgBAGIgCAFIgCAEIgDAFIAAAEIAAAMIgCANIgCAKIgEALIgFATIgFATIgDANQgDAJgEAIIgKASIgDAFIgCAGIgCAHIgCAFIgCAHIgCAHIgDAGIgDAGIABgDIgCAFIgDAFIgCAGIgDAFIgCAGIgDAEIgDAFIgEAGIgEAFIAAABIgBAHIgCAGIgCADIABACIAGAMIAGAMIAGAMIABACIAAAAIABABIAAAAIABACIAEADIADAFIADAFIADAFIADAFIAEAFIAEAEIAEAFIAFAGIAEAGIADAFIACAFIADADIALAOIAHALIAJAMIAJALIAIAMIAEAGIAJAKIAFAFIAEAEIAEAFIAEAEIAEAEIADAEIAEAFIADAEIAEACIAEADIAEAEIADADIADAFIADAEIABAFIABAFIABAFIgBAGIgBAFIgBAFIgDAEIgDAFIgDADIgEAEIgEADIgFACIgFACIgFABIgFABIgIAAIgIAAIgHAAIgIAAQgJABgJAEIgTAHQgLADgLABIgXACIgBABIgCAAIgBAAIAAABIgBAAIgBAAIgCABIgHACIgHACIgGAAIgGACIgHAAIgGAAIgHAAIgEABIgEACIgFACIgGAEIgGADIgFABIgHACIgGABIgGABIgHACIgFACIgGACIgNACIgNACIgNABIgLAAgArcDjIABABIgBgCIgBgBIABACgAmshfIAAACIABgCIAAgBgAFTHOIgFgCIgFgBIgFgCIgEgDIgEgEIgEgEIgCgFIgEgCIgDgCIgEgEIgFgEIgEgFIgEgDIgSgLIgKgHIgJgIIgJgJIgKgLQgHgHgIgHIgLgIIgLgJIgMgKIgFgEIgMgIIgFgEIgGgFIgEgEIgEgFIgEgEIgDgDIgIgCIgFgBIgGgDIgGgDIgFgBIgFgBIgGgCIgGgCIgGgDIgFgCIgBgBIgBAAIgFgDIgGgDIgFgBIgGgBIgGgCIgFgDIgEgDIgEgDIgDgEIgFgEIgDgGIgCgFIgCgGIgBgGIgBgFIAAgFIACgFIABgFIADgEIADgFIADgEIAEgEIAEgCIAFgDIACgBIAAgFIABgMIABgOIACgPIABgFIACgFIACgEIAAAAIAAgHIABgHIAAgFIAAgHIABgHIABgGIACgGIACgGIADgGIAAgHIAAgIIAAgIIABgHIAAgHIADgNIACgHIADgFIAAgFIAAgHIAAgGIAAgGIAAgHIABgMIABgHIABgHIABgFIACgGIADgGIAAgMIAAgbIAAgdIAAgpIAAgcIgBgOIgDgFIgCgGIgBgGIgBgGIgBgGIAAgGIAAgGIAAgGIAAgGIAAgHIAAgGIgBgGIgCgEIgCgEIgCgGIgBgGIgBgFIgCgGIgCgFIgCgGIgCgHIgBgIIgCgGIgCgFIgCgGIgCgFIgDgFIgDgEIgCgFIgCgFIgBgGIAAgGIAAgFIABgFIgCgCIgDgEIgCgFIgCgFIgBgFIAAgGIAAgFIABgFIACgFIACgFIADgEIAEgEIADgDIAFgDIAEgDIAFgBIAFgBQALgBAKABIAXAAIAXAAIAYAAIAXAAIAPAAIAFgDIAGgCIAFgCIAGgBIAGAAIAFgBIAGAAIAGAAIAGAAIAFAAIAGABIAFABIAEADIAEADIAEADIAEAEIADAEIACAFIACAFIABAFIADACIADADIAEAEIADAEIACAFIACAEIABAGQABA4gBA5IAABtIAAB2IAABZQABAQgEAQIgCAFIgCAFIgBAKIgBAPIAAAOIAAAKIgBANIgBAHIAAABIABACIABAAIAGAAIAGABIAHACIAGACIAFACIAeADIAdAGIAkAIIATADQAKADAKAEIABABIAGAAIAGABIAGABIAGACIAFADIAGACIAFABIAGABIAFADIAFACIAGACIAFABIAGABIAGADIAFACIAGACIABAAIAIABIAHAAIAHABIAGACIAGABIAFACIAFACQALACAKgBIAWAAIAWAAIATABQAJAAAIACQAIABAHADIAFACIAEAAIAGABIAFABIAFACIAEACIAEADIAEAEIAEADIADAFIACAEIACAFIAAADIACABIAFACIADAEIAEADIADAFIACAEIACAGIABAEIAAAGIAAAFIgBAGIgCAFIgCAEIgDAFIgEADIgDADIgFAEIgEACIgFABIgFABIgNABIgPgBIgHAAIgPABIgOAAIgBAAIgCABIgFACIgGADIgFABIgGAAIgFABIgMAIIgLAGIgKAFIgMAEIgOAEIgEADIgFADIgFACIgGADIgGADIAAAAIgFAEIgGADIgGADIgGACIgGACIgGADIgGADIgGACIgFADIgGADIgHACIgDABIgEACIgFADIgGACIgFABIgGACIgGADIgFADIgGADIgGADIgGACIgGACIgEABIgDACIgHAEIgDACIgEACIgGAEIgGADIgGAEIgGADIgDADIgEAEIgCACIgFAEIgFAEIgGACIgCAAIAAABIgEACIgFABIgFACIgGAAIgFAAgAA3B9IgBACIABgCIAAAAg");
	this.shape.setTransform(-61.8625,274.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6600").s().p("AGvHuIgFAAIgEAAIgGAAIgGgCIgGgCIgFgDIgFgEIgEgFIgEgFIgDgFIgCgGIgDgFIgCgGIgCgGIgEgGIgDgHIgDgGIgCgFIgFgDIgFgEIgFgDIgFgEIgFgDIgFgDIgGgDIgFgDIgFgDIgFgEIgFgEIgIgBIgHgBIgGgCIgFgCIgGgCIgFgDIgHgDIgGgDIgHgDIgEgCIgDgCIgGgEIgEgFIgFgDIgFgEIgFgEIgFgDIgFgFIgGgFIgDgCIgFgDIgEgDIgEgDIgFgDIgFgEIgFgFIgFgFIgFgEIgDgEIgCAAIgFgCIgFgCIgEgDIgEgEIgDgDIgDgFIgDgEIgBgFIgBgFIgBgGIAAgEIAAgEIABgGIAAgGIABgGIABgGIACgFIACgFIADgEIADgEIAEgFIAEgFIAFgEIAEgGIAFgEIAEgEIAEgEIAEgDIAEgCIgBgEIAAgFIAAgFIABgFIACgFIACgFIACgDIABgFIABgFIACgGIADgHIADgGIAEgLIADgMIAEgLIAEgKIAGgKIAGgKIAEgOIAEgNIAEgNIAEgKIAAgIIAAgHIAAgIIAAgHIABgGIABgFIABgEIgBgBIgDgFIgDgFIgCgEIgBgEIgDgEIgDgFIgDgFIgDgGIgFgMIgCgGIgKgOIgIgQIgEgJIgFgKIgEgLIgGgNIgDgEIgCgFIgCgGIgDgGIgCgEIgDgEIgCgFIgBgHIgBgHIgBgHIAAgBIgDgFIgCgFIgCgGIgBgGIgBgEIgBgFIgEgOIgFgOIgEgNIgDgMIgBgFIgCgDIgDgEIgEgEIgEgFIgCgFIgCgEIgDgGIgEgHIgEgGIgHgLIgGgKIgGgLIgEgLIgCgGIAAAAIgBgBIgBgFIAAgFIAAgBIAAgFIABgFIACgFIADgFIAAAAIACgEIAEgEIAEgDIAEgDIAEgCIABgBIAFgBIAFgBIAFgBIABAAIAGAAIAHAAIAHAAIAIABIAHgBIAEgCIAEgCIAFgCIAHgCIANAAIAMgBIATABIALABIALADIAHACIADABIACgCIADgDIAEgEIAEgDIAFgCIAFgCIAFgBIAFAAIAGAAIAFABIAEACIAFACIAEADIAEADIADAEIADAEIACADIADACIAEADIAEADIADAEIADAEIADAFIABAFIABAFIABAFIABACIADAFIAEAFIAEAGIAEAFIADAFIAEAGIADAFIADAGIAFAEIAFAFIAEAGIAEAGIACADIAFAFIAEAFIAFAFIAFAGIAFAHIACAEIADAGIAFAGIAFAHIAFAJIADAFIAGAMIAFAFIADAFIAEAGIADAFIAEAGIAEAFIAFAFIAEAEIADAFIADAFIAEAFIAEAEIAHAKIADAEIAEAJIADAEIADAFIADAFIAEAFIADAFIADAFIADAFIADADIADAEIADAEIACACIAFAFIAEAGIADAGIABAFIADAFIADAFIACAFIACAFIABAFIABAFIgBAGIgBAFIgBAEIABAEIABAFIABAGIAAAGIAAAGIAAAHIAAAGIAAAHIgBAOIgBAJIgBAGIgCAEIgCAFIgBACIgBAFIAAAFIgBAHIAAAGIgCAHIgBAGIgCAGIgDAGIAAABIAAAFIgBAGIAAAFIAAAFIgBAFIgCAFIgCAFIgCAFIgCADIgBAFIAAAFIgCAFIgCAGIgEAFIgBAGIgBAGIgBAGIgDAGIgCAFIgCAGIADABIAGAFIAGAEIAFACIAEACIAJAFIAFADIAFACIAIAFIAFACIAFACIAFADIAEADIAJAIIAFAEIAFAFIAGAEIAFADIAIAIIAEADIAEAEIALAJIAPAMIAJAJIAEAEIAGAEIAFAFIAKAIIADADIAFADIAEAEIAFACIAEACIADACIADADIAGACIAGADIAEACIAFABIAGADIAGADIAFAEIACABIAEADIAEADIAEADIADAEIADAEIADAFIABAFIABAFIABAFIgBAGIgBAFIgBAFIgDAEIgDAFIgDADIgEAEIgEADIgFACIgFACIgFABIgMAAIgOAAIgOAAIgPAAIgPAAIgHAFIgGAEIgGADIgGACIgGACIgHACIgcANIgbALIgaALIgRAGIgKAEIgFADIgFADIgGADIgGADIgOAFIgIAFIgEADIgFADIgEADIgFADIgGACIgFABIgGAAIgGABIgGAAIgBAAgAGClqIABABIgBgCIgBgBIABACgAEUl6IABABIgCgDIgBgCIACAEgAnrFbIgGgCIgGgCIgGgDIgFgEIgEgGIgEgGIgEgFIgFgGIgDgFIgEgFIgEgEIgHgEIgEgDIgFgDIgEgEIgFgEIgEgEIgFgEIgFgEIgQgLIgQgLIgQgLQgJgIgIgKIgJgPIgKgRIgDgFIgEgEIgEgEIgEgFIgFgGIgFgGIgCgFIgDgFIgCgCIgBgCIgHgDIgEgDIgEgDIgFgEIgFgEIgFgEIgFgFIgGgEIgEgDIgEgEIgEgDIgEgEIgFgEIgDgGIgDgFIgCgFIgCgGIgBgGIgBgFIAAgFIAAAAIgBgGIAAgOIAAgPIAAgOIAAgNIABgPIACgPIABgHIACgHIACgGIABgBIAAgIIABgHIABgIIACgFIACgGIACgFIABgCIAAgGIAAgHIAAgGIAAgHIABgHIABgHIABgGIACgGIACgGIACgGIACgHIABgGIAEgFIAEgFIAEgFIAFgDIAGgDIAGgCIAGAAIAHAAIABAAQAugSAzAFQAfACAeAAIBlAAIBYAAIAUAAIAAAAIgEgFIgDgFIgEgGIgCgFIgCgFIgCgGIgDgEIgDgFIgCgFIgCgHIgBgGIgDgGIgDgGIgCgFIgCgEIgFgOIgDgHIgCgFIgDgFIgDgEIgDgEIgDgFIgCgHIgBgGIgEgFIgEgFIgEgFIgDgGIgGgLIgDgFIgDgEIgDgEIgDgFIgBgFIgCgFIgBgFIAAgFIAAgFIAAgFIAAgFIABgFIACgFIACgFIADgEIAEgEIADgDIAFgDIAEgDIAFgBIAFgBIAGgBIAFABIAFABIACgCIAEgDIAFgDIAFgBIAFgBIALgBIAMAAIAGAAIAHAAIAGAAIAGABIAGAAIAGABIAGACIAFACIAGADIAPAAIAQAAIAIAAIAGAAIAFAAIAGAAIAFAAIAJAAIABgCIAEgEIADgDIAFgDIAEgDIAFgBIAFgBIAGgBIAFABIAFABIAFABIAFADIAEADIAEADIADAEIADAEIADAFIABAFIABAFIABAFIAAAHIAAAGIACAEIgBgBIABABIAAABIAAgBIAAACIAAAAIABABIACAGIADAHIACAGIADAHIADAFIADAFIACAFIACAEIADAFIADAFIACAFIACAHIACAGIADAFIACAGIACAGIABAHIABAHIADAFIACAGIADAHIACAHIACAGIADAFIACAGIgCgFIgCgFIAIASIAIAOIAJASIAHAOIAKAUIAFANIADAHIADAEIACAFIACAEIACAHIACAHIACAFIADAGIACAFIgCgFIgCgEIADAFIADAFIADAGIADAFIABAGIABAFIABAGIACABIADAFIABAEIACAFIABAFIAAAGIAAAFIgBAFIgCAFIgBAFIgDAEIgDAEIgEADIgFADIgEACIgEADIgFADIgFACIgHABIgHACIgEACIgFACIgFACIgGACIgHACIgGAAIgHABIAAAAIgGACIgFACIgFACIgIABIgHABIgFABIgFACIgFACIgGACIgGACIgHAEIgGACIgEABIgEABIgEADIgFABQgIADgIABQgJACgJAAIgRABIgXAAIgUAAIgGAAIgBAAIgGACIgHADIgGABIgHACIgGAAIgGABIgHAAIgBAAIgFADIgGACIgGABIgFABIgGABIgGAAIgIABIgIAAIgEACIgGADIgGACIgHABIgHABIgEAAIgBAAIAAADIAAATIgBAVIgEAWIgCAGIgCAGQgBATAAATIAAAlQAAAWgGAVQgEAOgFANIgCAHIgBABIAAAHIgBAIIgBAHIgBAHIgCAHIgDAGIgCAFIAAABIgBAFIgBAFIgDAEIgCAFIgEAEIgFAEIgFADIgGACIgGACIgGAAIgGAAgAmiB0IAAACIABgCIAAgBgAk+AQIABAAIACAAIgCAAIgBAAgAr8g+IAAABIABgBIAAgCIgBACg");
	this.shape_1.setTransform(-72.425,275.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF9933").s().p("AD6HuIgOAAIgOAAIgNAAIgOAAIgMgBIgGgBIgFAAIgGgBIgGgCIgLgGIgLgGIgLgHIgFgEIgGgEIgEgEIgGgEQgJgHgLgEIgSgHIgSgHIgRgHQgNgFgOgHIgLgHIgGgBIgGgBIgGgCIgHgCIgHgDIgFgCIgFgDIgEgDIgFgEIgDgFIgEgFIgCgGIgCgGIAAgGIAAgDIgBgCIAAgFIAAgFIABgFIABgFIADgFIADgEIADgFIAAAAIADgEIAEgFIACgEIAEgFIADgFIADgFIAEgFIAEgSIAGgTIAGgTQAGgMAHgMIABgGIADgHIACgHIADgDIACgDIADgFIADgFIACgOIADgOIAFgNIADgMIAEgMIACgGIAAgGIAAgGIACgGIACgFIADgFIACgEIAEgFIADgFIAAgBIgEgDIgFgFIgGgEIgDgEIgEgFIgDgEIgDgFIgFgEIgDgEIgEgEIgDgFIgEgEIgDgFIgDgGIgEgEIgDgEIgDgFIgDgFIgDgEIgCgEIgBgBIgBgCIgBgBIAAABIgCgDIgCgEIgEgEIgDgFQgSgVgUgUIgRgPQgfgagigWQgigUgkgPQgegMgcgRIgRgLIgUgQQgSgMgUgKIgmgSQgSgKgRgLIgggYIgVgPIgFgCIgFgCIgEgDIgFgDIgDgEIgDgFIgDgEIgBgEIgEgGIgCAAIgEgDIgEgDIgDgEIgDgFIgCgFIgCgEIgBgGIgBgHIABgGIADgGIACgGIADgEIAEgEIADgEIAEgCIAFgDIAFgBIAGgCIAHAAIAGABIAFACIAHADIAGACIAEAEIAGAEIAFgEIAGgDIAHgEIAEgDIAFgEQAOgIAQgGQARgHATgCQASgCASAAIAbABIAIAAIAAgBIAEgDIAFgCIAFgCIAFgBIAGAAIAGAAIAGABQARAFAPAKIARAMIAVATIATASIAGAEIAEAEIAFAEIAEAEIAFAEIAEAFIAEADIABABIADAFIAGAEIAEAFIAFAEIADADIADAEIADAFIAFAEIADACQAbAEAZAIQAZAIAXAMQAYANAVASQALAKAIAMIADAEIAFADIADAEIACABIALAGIAMAIIALAIIARANQAJAJALAGIAKAGIAHADIAGACIAGADIAGADIAGAEIAFAFIAGAEIAGAFIAEADIAFADIAEADIAFADIAEADIACACIAAAAIAAAAIAAAAIABABIAEACIADACIAFACIAEADIAEADIAEAFIAFAEIAEAFIAEAFIAEAFIADAFIAEAFIAGALIAEAEIADAFIAEAFIAEAFIAFAFIAEAFIAFAEIADAEIADAFIACAEIACAFIABAFIAAABIACACIAEAFIADAEIADACIAEACIAEABIAFABIAFADIAEACIAEAEIAEAEIADAEIACAFIABAFIABAFIABAEIgBAFIgBAFIgBAFIgCAFIgDAEIgDAEIgIAVIgFAMIgGALQgEAJgGAHIgGAIIgGAIIgDAEIgDAFIgDAGIgEAFIgDAFIgDAEIgDAEIgBAEIgBAEIgCAGIgEAGIgBAGIgBAFIgCAGIgCAFIgDAGIAAABIAAAFIgBAEIAAADIASAGIAYAKIAGACIADAAIACABIAAAAIABAAIABAAIgBAAIADAAIAHABIAHABIAGABIAMAFQAJACAIADIAHACIAFADIADABIAFACIAGADIAFADIAQAFIANAGIALAFIAJAFIAKAEIAEADQAKAAAKADIAFABIAGACIAFADIAGACIAEADIAEADIABABIADADIAEAEIADAEIACAFIACAFIABAFIABAFIgBAGIgBAFIgCAFIgCAEIgDAFIgEADIgDAEIgEADIgFACIgFACIgFABIgMAAIgPAAIgOAAIgNAAIgHACIgFABIgGACIgGACIgEACIgGADIgFACIgGABIgGACIgFAEIgGAFIgFAEIgGAEIgGAFIgFAEIgGAEIgGAFIgEAEIgGAFIgDAFIgDAFIgEAEIgEAFIgFAFIgEAEIgFADIgGAEIgEADIgCAEIgBADIgFAFIgDAFIgGADIgEADIgGACIgCABIgBABIgFABIgGABIgNABIgGAAg");
	this.shape_2.setTransform(-61.2,276.6083);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF6600").s().p("AikISIgGAAIgHgCIgHgCQgQgJgNgKIgXgTIgYgUIgYgTIgbgVIgOgMIgEgEIgFgCIgFgFIgGgEIgFgFIgGgEIgFgFIgEgEIgFgFIgFgEIgGgEIgHgEIgFgBIgHgCIgGgBIgEgEIgGgDIgFgEIgFgEIgDgEIgDgEIgEgDIgDgEIgDgEIgEgGIgDgFIgDgEIgDgEIgBgFIgBgBIgOAGIgHABIgGABIgGgBIgEgBIgGgBIgFgDIgEgDIgDgDIgEgEIgCgEIgDgFIgCgFIAAgCIgCgEIAAgGIAAgFIABgFIACgFIADgFIACgEIAEgEIAEgDIAEgEIAFgCIAEgBIAHgBIAqgbIAigYQARgMATgJIAegOQAGgCAIgCIAEgEIAEgEIAFgDIAEgEIAFgDIAWgVQAMgMAOgLQALgJAJgKIAPgSIAEgDIAEgDIADgEIAEgFIAFgEIADgFIADgDIAEgEIAEgDIAFgCIAFgCIADAAIABgDIADgEIACgEIADgEIADgGIADgGIADgEIAEgEIADgDIAFgDIACgFIADgFIAEgDIADgFIAGgEIAFgEIAGgDIAGgEIADgDIAFgDIAEgEIAHgNIAGgOIAGgLIAHgMIACgFIADgFIAFgGIAEgFIAEgGIADgGIADgEIADgFIADgDIADgEIADgFIADgGIAEgFIAEgFIAEgGIAEgFIAEgGIAEgGIADgGIAEgGQAHgTALgPIARALQAcAQAeANQAkAPAiAUQAiAWAfAaIARAPIgCADQgJAPgNANIgHAHIgLARIgMARIgJAMIgJALIgGAIIgCACIgTAYIgTASQgMANgKAOIgUAeIgKAQIgIATIgIAQIgEAJIgGALIgFAKIgGAJIgDAGIgIAJIgEAFIAFAGIACAFIACAEIABAEIADADIABABIABABIACAEIAFAGIADAFIADAGIAEADIADADIAIAIIAHAKIAIALIADAFIADAGIAEAEIAJAJIADAFIAFAEIAKAKIAEAGIAGAEIALAGIAMAHIARAJIANAGIAHAEIAFADIAEAAIAFABIAFACIAEADIAFACIADAEIAEAEIADAEIACAFIACAFIABAEIAAAGIAAAFIgBAGIgCAEIgCAFIgDAEIgEAEIgDADIgFAEIgEACIgFACIgFAAQgRACgSgBIgsAAIgjAAIghAAIgSAAIgGABIgGACIgGACIgGABIgFABIgGABIgGACIgGAEIgGADIgFAEIgHAEIgGADIgFAFIgHADIgDAFIgEAEIgDAEIgFADIgDACIgFAFIgFADIgGAEIgFADIgGACIgFADIgFADIgHADIgHADIgFADIgDADIgEAEIgFADIgEACIgFABIgEABIgGAAgAhZAFIgCABIACAAIABgBIgBAAgAF+kvIgDgEIgFgDIgDgFQgIgMgLgJQgVgSgZgNQgXgMgZgIQgZgIgbgEIgDgCIgFgFIgDgEIgDgEIgDgDIgFgFIgEgEIgGgFIgDgEIgBgBIAKgJIAYgWQAMgKANgJQAGgDAGgCIAAgBIACgFIADgGIACgEIAEgDIAEgEIAFgCIAEgCIAFgDIAFgBIAFAAIAFAAIAGABIADACIAGABIAHABIAFACIAGABIAFACIAFAAIAHAAIAFAAIAAAAIAFgDIAGgCIAFgBIAHgCIAHgBIAGAAIAHAAIABgBIAGgCIAGgCIANgCIANgCIAOAAIAVAAIAOAAIALABIAGABIAEACIAFACIAEADIAEAEIADADIADAFIADAEIACAFIAAAFIABAGIgBAFIAAAFIABABIADAFIADAEIACAGIABAEIAAAGIAAAGIgBAFQgEARgMANIgTAVQgOAPgQANIgiAZIgYASIgFAEIgFAFIgFAEIgDAFIgCgBg");
	this.shape_3.setTransform(-92.6,280.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF9933").s().p("AJSGAIgFgBIgFgCIgFgCIgEgDIgCgCIgLABIgMAAIgNgBIgNgBIgMgCIgLgEIgFgCIgEgDIgEgDIgBgBIgFgDIgEgCIgEgDIgEgDIgEAAIgGAAIgGgBIgHAAIgGgBIgGgBIgFgCIgFgCIgEgBIgDgBIgHAAIgHAAIgGgBIgHAAIgGgBIgHgBIgFgCIgFgCIgFgCIgGAAIgMAAIgLAAIgLAAIgMgBIgLgDQgIgCgHgDIgBAAIgFgBIgFAAIgGAAIgGgBIgGgBIgGgBIgFgBIgGgCIgFgDIgCAAIgFgBIgEAAIgEgBIgGgCIgFgCIgGgDIAAAAIgHAAIgHgBIgGgBIgGgDIgFgCIgFgCIgEgCIgBgBIgFgCIgEgCIgFgCIgBAAIgGgCIgGgBIgGgCIgGgDIgFgEIgFgBIgEgCIgFgDIgFgEIgFgEIgEgDIgFgEIgEgEIgDgFIgEgEIgDgFIgDgFIgCgGIgBgFIAAgGIAAgGIgCgCIgEgEIgDgEIgDgFIgDgCIgFgFIgCgDIgDgCIgDgEIgDgEIgCgEIgGgEIgFgEIgGgEIgGgDIgFgCIgDgDIgFgDIgKgHIgEgEIgGgEIgGgEIgFgCIgFgCIgFgCIgEgEIgEgDIgEgDIgBAAIgFgEIgFgDIgFgEIgFgEIgFgFIgDgGIgDgFIgCgEIgCgDIgFgFIgEgFIgCgDIgCgEQgGgFgHgDIgWgNQgNgGgMgIIgSgMIgNgHIgJgCIgOgFIgMgEIgRgIQgIgEgGgFIgHgCIgHgDIgHgDIgFgCIgFgDIgFgDIgFgCIgHgDIgGgDIgGgDIgGgDIgFgEIgLgIIgDgEQgKgCgJgFIgZgMIgCgBIgTgJIgPgKQgHgGgIgEIgDgCIgGgCIgMgEIgGgCIgFgCIgGgDIgKgHIgKgHIgGgDIgFgDIgFgDIgGgDIgGgFIgGgEIgEgEIgEgEIgFgEIgEgFIgFgEIgMgGIgJgEIgLgGIgNgHQgIgEgIgCIgFgDIgEgDIgEgDIgBgBIgEgCIgDgDIgFgDIgEgEIgEgEIgFgEIgEgFIgFgEIgEgFIgGgFIgFgCIgFgDIgFgDIgFgCIgFgEIgGgEIgEgFIgEgEIgDgEIgCgFIgCgFIgBgFIAAgFIAAgFIABgFIACgFIACgFIADgEIADgEIAFgEIAEgCIAFgDIAEgBIAGgBIAFgBIACAAIABAAIAEgDIAFgDIAFgBIAFgBQAOgBAOAAIAeAAIAeAAIAfAAIAmAAIAJAAIACAAIAFAAIABAAIALgEQAKgDAKgBIAAAAIAHAAIAggBIACAAIApAAIA6AAIADAAIA0ABIAFABIAFABIAEADIAFADIABABIAFABIAFAAIAHADIAHACIAGAEIAJAGIAEAEIAEADIAFAEIAEAFIAEAGIAFAGIADAFIACAEIAKALIAEAFIAFAFIAFAFIAEAFIAEAGIADAEIACAGIAEADIAKAGIAFAEIAEADIAJAIIAKAJIAFAFIAEADIAFACIAEADIAEADIAFAEIACABIAEAEIAFADIAFAEIAFAEIAGAEIAFAEIAFADIAEAEIAKAFIAJAGIAIAIIAJAJIAJAIIADACIACABIAFADIAFADIAFAFIAGAEIAFAFIAGAFIAEACIAFADIAFADIAFADIAGACIAFADIAFABIAEABIAFACIAFADIAFACIAEADIAFADIAFAEIAFADIAFACIAFACIADACIAGABIAGACIAFACIAFADIAEADIAFACIAFACIAFACIADADIAEADIAFADIAFADIABAAIAFABIAEABIAFACIAEACIAEACIACAAIAAAAIAFgDIAEgDIAFgBIAFgBIAGgBIACAAIAFgBIAFgCIAFgCIAGgBIAFgCIAHgDIAHgCIAHgCIAGgCIAGAAIAGgBIAFgDIAGgCIAEgBIAEgBIADgCIAFgCIAGgCIAFgCIAGgBIAFgBIAFgBIAFAAIAEAAIAGgDIAGgCIAHgCIAGgCIAHgCIAIgCIAGgDQANgBANgEQAPgEAPgCQAOgBAOAAIAeAAIAOAAIABAAIAGgCIAHgDIAGgBIAHgCIAGAAIAHgBIAGAAIANgDIAMgDIAPgCIAPgBIACgBIAGgCIAFgCIAGgBIAFgCIAFAAIAFAAIAFABIAFACIAFACIAEADIAEADIAEAEIADAFIACAEIACAFIABAGIAAAFIAAAFIgBAFIgCAFIgCAFIgDAEIgDAEIgEADIgEADIgFADIgFABIgDABIAAADIgBAFIgCAFIgCAGIgCAEIgDAFIAAACIgDAHIgDAGIgDAFIgEAFIgFADIgDADIgDADIgDADIgDAEIgDAGIgDAFIgBACIgCAHIgDAGIgEAFIgEAGIgDAFIAAAIIAAAHIAAAIIAAAHIAAAIIABACIACAFIACAFIACAGIABAGIABANIAAANIAAALIAAAGIABABIACADIACAFIACAEIABAFIACAFIABAFIAAAAIACAFIACAFIABAFIABAFIAAAFIABAIIAAAHIgBAOIgDALIgEAMIgDAFIgEAFIgDAEIAAAPIAAAPIAAAOIAAAPIAAAOIAAAGIgBAFIgCAFIgCAEIgDAFIgEADIgDAEIgFADIgEACIgFACIgFABIgGAAIgFAAgAIwCAIABACIAAgCIgBgBIAAABgABMBSIACAAIgCgBIgCAAIACABgAj6kkIABAAIgBgBIAAAAg");
	this.shape_4.setTransform(-49.775,265.5917);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF6600").s().p("AjLHQIgGgBIgEgBIgGgDIgEgDIgDgDIgJgEIgMgGIgLgGIgKgHIgOgHIgMgIIgMgIIgMgIIgKgJIgKgIIgNgIIgNgHIgLgHIgKgIIgKgJIgKgKIgGgEIgGgEIgGgDIgGgDIgHgDIgFgEIgGgCIgHgCIgFgDIgGgDIgGgDIgFgDIgGgDIgEgDIgGgCIgGgFIgFgEIgFgFIgEgGIgEgDIgDgEIgGgFIgGgEIgFgFIgDAAIgFgCIgEgCIgFgDIgDgEIgEgDIgDgFIgCgEIgCgFIgBgFIgBgGIAAgHIAAgIIABgGIACgGIACgGIADgFIADgGIADgGIADgFIAEgGIADgFIAEgFIADgEIACgEIADgDIADgEIABgCIACgHIADgFIABgHIAAgIIAAgPIAAgOIAAgPIABgFIABgGIAAgCIAAgEIAAgFIAAgGIABgFIABgFIADgFIAEgFIADgDIADgEIAFgDIACgBIAFgEIACgDIACgEIADgFIAEgEIABgBIABgFIAEgHIADgGQAFgNAGgKIAKgPIANgOIANgOIAOgOIAJgJIAIgLIADgGIAEgFIAFgGIAZAMQAIAEALACIADAFIAKAHIAGAEIAGAEIAGADIAGACIAHADIAEADIAGADIAEACIAGADIAHADIAHADIAGACQAHAFAIADIARAIIAMAFIAOAEIAJADIANAIIASALQAMAIANAHIAWAMQAHAEAGAFIACADIACAEIAEAFIAEAEIACADIADADIADAGIADAFIAFAFIAEAEIAGAEIAEAEIAFADIACABIgQgEQgWgGgXgHQgRgGgRgHIAAABIgDAFIgDAFIADAEIADAFIACAFIAEAEIAFADIADAEIAFAEIAEAFIAFAFIAEAEQAOAKAMAMQAIAGAIAFIAOALIAPANIAQAPIAKALIACABIACAAQALAFAJAGIAKAGIAJAIIAJAHIAKAHIAKAIIAGAEIAGAEIAGADIAHAEIAQAHIAMAGIAKAGIAKAFIAJAEIAJAFIAEACIAFABIAHACIAFACIAFADIAGAEIADABIAFACIAEADIADAEIAEADIADAFIACAEIACAFIABAFIABAGIgBAFIgBAFIgCAFIgCAFIgDAEIgEAEIgDADIgEADIgFADIgFABIgFABQgZABgaAAIg8AAIg6AAIgxAAIgHAAIgMAIIgMAIIgKAJIgNALIgPALIgKAHIgBACIgCADIgCAEIgEAGIgEAFIgEAEIgDAFIgDAFIgDAFIgDAEIgEAEIgDAFIgCAEIgDAFIgDAEIgDAEIgEADIgEADIgFACIgEABIgFABIgFABIgFgBgAoWD5IgBgBIAAAAgAI5A5IAAgCIABACIAAABIgBgBgAAdjgIgJgJIgJgIIgJgIIgIgGIgKgGIgFgDIgEgEIgGgEIgFgEIgFgEIgFgEIgFgDIgFgDIgCgCIgEgDIgEgDIgEgEIgFgCIgEgCIgFgFIgKgJIgJgIIgEgEIgFgDIgLgHIgDgDIgDgFIgCgFIgEgFIgFgGIgEgFIgFgFIgEgFIgKgKIgDgFIgCgFIgFgGIgEgGIgFgEIAEgDIAFgEIAGgFIAFgCIAFgCIAGgCIAFgBIAGAAIAGAAIAFAAIAGABIAEACIAFACIACgBIAHgCIAGgBIAGABIAGABIAFABIAEADIAFACIARAAIAYAAIAYAAIAWAAIAQAAIAEgDIAFgCIAFgCIAGgCIAIgCIAFgCIAFgCIAFgBIAFgBIAGgBIAEgDIAEgCIAEgBIAGgCIAFgBIAFAAIAGAAIADAAIAGAAIAEABIAGACIAEACIAFADIAEADIAEAFIACAEIACAFIACAFIABAFIABAFIgBAFIgBAFIgCAFIgCAFIgCAEIgFAEIgDAEIgFAEIgDAGIgDAFIgBAGIgCAGIgCAGIgDAHIgEAFIgEAFIgFAGIgEAGIgFAFIgFAKIgDAEIgDAFIgIAJIgEAEIgKAIIgFAFIgEAGIgFAFIgEAFIgFAFIgEAIIgGAJIgIAJIgCgBgAjxlsIAAAAIAAAAIABABIgBgBgAnlm9IAFgBIgBABIgEAAgAnRnDIAHgBIAHgBIADAAQgLABgJADIADgCgAm8nGIADAAIgHABIAEgBgAlunGIgqAAIABgBIAFgDIAEgDIAFgBIAGgBQAcgDAdAGQALACALAEIg6AAg");
	this.shape_5.setTransform(-50.65,272.7109);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_3},{t:this.shape_2}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_3},{t:this.shape_2}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_3},{t:this.shape_2}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape}]},2).wait(2));
	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},2).wait(6).to({_off:false},0).to({_off:true},2).wait(6).to({_off:false},0).to({_off:true},2).wait(6).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-303.3,-59.6,382.6,392.90000000000003);


// stage content:
(lib.Holley_DuckCharacter = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		document.addEventListener("keydown", handleKeyDown);
		
		var root = this;
		
		function handleKeyDown(event) {
			console.log("hello");
			switch (event.keyCode) {
				case 32: // spacebar
					root.duck_mc.gotoAndPlay("standing");
				break;
				case 13: // enter
					root.duck_mc.gotoAndPlay("walking");
				break;
			}
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer_1
	this.duck_mc = new lib.walking();
	this.duck_mc.name = "duck_mc";
	this.duck_mc.setTransform(912.3,600.2,1,1,0,0,0,-112,131.8);

	this.timeline.addTween(cjs.Tween.get(this.duck_mc).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(1681,948.8,-577.4000000000001,-157.0999999999999);
// library properties:
lib.properties = {
	id: '3DB5E895FE564E20AF70FC7B632BC79B',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Holley_DuckCharacter_atlas_1.png?1779238479334", id:"Holley_DuckCharacter_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3DB5E895FE564E20AF70FC7B632BC79B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;