(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"Holley_DuckCafeFinal_atlas_1", frames: [[0,0,1281,934]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_2 = function() {
	this.initialize(ss["Holley_DuckCafeFinal_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AnZISIgzAAIglAAIgHgBIgGgBIgHgBIgGgCIgGgDIgGgDIgEgDIgFgEIgEgDIgGgFIgGgFIgFgCIgEgDIgFgDIgEgDIgFgFIgEgEIgEgGIgEgGIgDgEIgDgGIgCgEIgFgFIgDgEIgDgGIgCgFIgBgGIgBgHIABgGIACgGIADgGIADgEIADgEIAEgDIAEgEIAFgCIAFgCIAFAAIAFgBIAGABIAFAAIAFACIAFACIAEAEIAEADIAEAEIAEADIADAEIACAFIADAEIADAGIAEAHIAGACIAFAFIAGAEIAFADIAFAFIAFAEIAcAAIAbAAIAbAAIAdAAIAbgBIAHAAIABAAIAFgDIAFgDIgCgCIgCgDIgDgEIgDgGIgCgGIgBgGIgBgGIAAgIIAAgJIAAgHIABgLIACgMIABgFIACgFIADgFIAEgEIAEgFIAFgDIAGgDIAFgCIAHgBIANAAIAPAAIAQAAIAPAAIAPAAIABgBIAFgDIAFgFIgCgDIgBgEIgBgBIgDgDIgEgFIgEgEIgDgEIgDgEIgDgFIgFgFIgFgFIgFgFIgEgFIgEgEIgDgEIgCgFIgCgFIgBgFIAAgFIAAgFIABgFIACgFIACgFIADgEIADgEIAFgEIAEgDIAFgCIAFgBIAFgBIAFgBIAFABIAFABIAFABIAFACIAEADIAEAEIAFAEIAEAFIAFAEIAEAFIAEAEIAEAFIADAEIAEAFIACADIAEAEIAEAEIAEAEIADAFIADAFIADAFIACAGIADAEIADAFIADAFIACAFIABAHIABAHIAAAGIABAHIgBAGIgBAFIgBAGIgCAGIgDAEIgDAFIgDAFIgEAFIgFAEIgFAEIgGADIgGAEIgFAFIgGAEIgGAEIgHADIgHACIgFACIgFABIgFABIgFAAIgGABIgHAAIgGAAIgGAAIADADIADAEIADAEIACAFIACAEIABAHIABAGIABAGIgBAGIgBAGIgCAEIgCAGIgCAEIgDAFIgEAEIgDAFIgEADIgFADIgEAEIgmATQgVAMgZAAIg0AAgADNF8IgXAAQgRAAgRgDIgbgEIgcgHIgdgJQgOgEgOgCIgcgEQgPgDgQgFQgNgDgLgFIgGgCIgGgBIgEgDIgFgDIgDgDIgEgFIgCgEIgDgFIgBgEIgBgGIgBgEIABgGIABgFIABgFIADgFIADgEIADgEIAEgEIAFgCIAEgCIAFgCIAFgBIAFgBIAGABIAFABIAFACIAGACIAFACIAGACQAVAHAXADQAXADAXAGIAxANQAhAKAhgBIA6gBIAAgHIAAgIIAAgIIAAgHIAAgGIAAgGIAAgGIgBgGIgCgGIgBgGIgBgFIAAgGIACgGIABgFIADgFIACgEIAEgDIAEgEIAEgDIAFgDIAGgCIAGgCIAHAAIAFAAIAGABIAFACIAFAEIAFACIAFACIAEADIACAAIAHAAIAHAAIAFgCIAGgCIAGgBIAGgCIAHgBIAGgBIAHgCIAFgBIAFgBIAEgCIAHgCIAHgDIAHgCIABgBIABgHIAAgHIAAgHIAAgHIAAgIIAAAAIAAgHIAAgHIAAgHIAAgGIABgEIACgFIACgFIADgEIAEgEIADgEIAFgCIAEgDIAFgCIAFgBIAGAAIAFAAIAFABIAFACIAFADIAEACIAEAEIADAEIADAEIADAFIABAFIABAEIABANIAAAOIAAAAIAAAPIAAANIAAAPIgBAPIgBAHIgCAEIgCAFIgCAFIgDADIgDAFIgEAEIgKAIIgKAGIgJAEIgLAEIgLAEIgMAEIgLAEIgLACIgMACIgOAEIgMACIgNADIgMAAIgEABIAAANIgBAPIgCANIgEAMIgEAMIgFAJIgDAEIgDAFIgFADIgEADIgFADIgFACIgGACQgNADgOABIgZAAIgdAAgAh4AUIgkAAIgPAAIgGAAIgGgCIgFgBIgGgBIgFgBIgFgCIgFgCIgHgCIgIgCIgFgCIgGgDIgFgDIgFgDIgFgEIgFgEIgEgEIgEgEIgDgDIgCgFIgCgEIgBgFIAAgEIAAgGIABgEIABgFIACgEIACgFIACgEIAEgEIAEgDIAGgEIAFgCIAHgCIAGAAIAGAAIAGACIAGACIAFAEIAFADIACACIgCgBIACABIABABIgBgBIACACIACABIAHADIAHABIAIADIAHACIAWABIAXgBIAVAAIAWAAQAKAAALAAIAAgBIAHgEIAHgDIAEgFIAFgEIAAgGIAAgGIAAgFIAAgFIAAgEIAAgHIABgFIABgGIADgHIADgHIACgEIAEgDIAEgEIAEgDIAFgCIAFgCIAEgBIAGgBIAGABIAGACIAGACIAHAAIAIAAIAHAAIAHAAIAIAAIAHAAIAIAAIABgBIAFgDIAEgCIAEgDIAFgEIAGgCIAGgCIAGgCIAAgCIAEgEIAEgFIACgFIAAgHIAAgHIAAgIIAAgGIAAgOIgBgGIAAgHIgBgGIgCgFIgCgGIgCgGIgCgGIgDgFIgDgGIgCgGIgCgHIAAgHIAAgGIABgEIACgGIACgEIADgFIAEgDIADgDIAFgEIAEgCIAFgBIAFgBIAGgBIAFABIAGABIAFACIAEACIAFADIAEADIADAEIADAFIACAFIAEAFIACAGQAJAXAEAZQAFAZAAAZQABAdgLAaQgJAWgRAQQgOANgUAGIgSAMQgJAFgKACIgNACIgNACIgUAAIgJAAQgBAMgEAKQgEAJgFAHIgLAOIgNAMQgFAFgHADIgVALQgQAFgRABIgdAAIgdAAgAH9jRIgRAAIgKAAIgGgBIgFgBIgGgBIgFgDIgFgCIgFgDIgEgDIgFgEIgEgDIgFgFIgGgEIgEgFIgEgDIgFgFIgEgEIgFgDIgGgDIgGgBIgGgDIgGgEIgEgCIgFgEIgEgEIgFgDIAAAAIgFgDIgDgEIgEgDIgDgFIgCgFIgCgFIgBgGIAAgGIABgHIACgGIACgFIADgFIAEgDIAEgEIAEgDIAEgCIAFgBIAHgCIAGAAIAGABIAGACIAGACIAFADIAFAEIAFAEIAEAEIAOAFQAJAEAIAFQAJAHAHAHIAJAIIAJAJIAEAEIAHAAIAGAAIAGAAIAHAAIAHAAIAHgBIAHAAIgEgGIgGgLIgGgKIgHgKIgGgNIgGgNIgCgGIgBgFIAAgHIABgHIACgFIADgGIAEgEIAFgFIAFgDIAEgDIAFgCIAEgBIAHgCIAMAAIAMAAIANAAIANAAIAOAAIAAgFIAAgIIgBgHIAAgHIgBgBIgCgFIgDgEIgDgGIgEgEIgEgFIgEgEIgDgEIgCgFIgCgFIgBgFIAAgFIAAgFIABgFIACgFIACgFIADgEIADgEIAFgEIAEgDIAFgCIAFgBIAFgBIAFgBIAFABIAFABIAFABIAFACIAEADIAIAIIAIAJIAIALIAHALIAFAKIAEAJIACAFIABALIACALIAAAMIABAOIAAANIgBANIgCAGIgBAGIgDAHIgCAEIgDAGIgEAEIgEAFIgEAEIgFADIgEADIgFABIgGACIgFABIgFABIgGABIgFABIgGAAIADAFIACAGIACAGIABAEIABAFIABAHIABAHIAAAHIgCAIIgCAFIgCAFIgCAFIgIAKIgIAKIgJAJIgKAIIgFADQgIAFgJACIgSACIgTABIgMAAg");
	this.shape.setTransform(68.275,53);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,136.6,106), null);


(lib.Symbol3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(6,1,1).p("Aqxj/IgPhtILAAAIC5AAIIIAAIgSCWAAAlsIAAtwIC5jSIAARCAKri4IjGZnIurAAIjh5q");
	this.shape.setTransform(70.475,145.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#66FF99").s().p("Am9N2Iji5pIgFgDIgEgDIgEgDIgDgEIgDgEIgDgFIgBgFIgBgFIgBgFIABgGIABgFIABgFIADgEIADgEIADgEIAEgDIAAgBIAEgCIAFgDIAEgCIAGgBIAEAAIAFgCIAGgDIAGgCIAGgBIAFgBIAEgCIADgCIAHgDIAGgCIAGgCIAHgDIAHgCIAGgCIAGgBIAIgBIAFAAIAGgBIAGAAIAHgCIAGgDIAGgCQA6gPA+ABIBwABIB9AAQA4AAA5gDQAogCAkANIABABIAHAAIAFABIAHAAIAGABIAFABIAHABIAGADIAGACIAGACIAGABIAGACIAGADIAGACIAIACIAHACIAHACIAOAFIAMAEIAGADIAGACIAGACIAGABIAGACIAGADIAHADIABAAIAHAAIAGABIANABIAMABIANACIALADIAFACIAIAAIAIAAIAQABIAKABIALACIAMADIAFACIAEABIAGABIAGABIAHABIAGABIAHACIAIACIAHACIANAAIAPABIAOAAIAPAAIAPABIAMACIAFABIAEADIAEACIAHAAIAHABIAHAAIAHAAIAGAAIAIAAIAIAAIAIAAIAGgDIAGgCIAFgCIAGgBIAFgCIAHgDIAGgCIAGgCIAGgBIAGgCIAFgCIAGgCIAMgEIAOgBIAMgBIAOAAIAMAAIAFABIAFACIAFACIAEADIADAEIAEADIADAFIACAEIACAFIABAFIABAGIgBAFIgBAFIgCAFIgCAEIjGZng");
	this.shape_1.setTransform(69.65,202.3367);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(-3,-3,147,297), null);


(lib.Symbol2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FF0000","#FFFF00","#00FF00","#00FFFF","#0000FF","#FF00FF","#FF0000"],[0,0.165,0.365,0.498,0.667,0.831,1],-129.8,0,129.8,0).s().p("AuVOWQl8l8AAoaQAAoZF8l8QF8l8IZAAQIaAAF8F8QF8F8AAIZQAAIal8F8Ql8F8oaAAQoZAAl8l8g");
	this.shape.setTransform(129.8,129.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,259.6,259.6), null);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AOmzLIsV5GIwCZGIcXAAMAAAA1cIJeKBMgwHAAAIJ4qBIAaAAIcXAAEgNxAiRMAAAg1c");
	this.shape.setTransform(153.975,283.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("EgYDAsSIJ4qBIAaAAMAAAg1cIcXAAMAAAA1cI8XAAIcXAAIJeKBgAOmzLgAtxzLIQC5GIMVZGg");
	this.shape_1.setTransform(153.975,283.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-1,-1,310,568.8), null);


(lib.head = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// pupil
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLAAQAAA6gpAoQgoApg6AAQgTAAgSgFQgigJgbgbQgogoAAg6QAAg4AogqQAbgaAigJQASgFATAAQA6AAAoAoQApAqAAA4g");
	this.shape.setTransform(18.3,-14.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AglCGQgigJgagbQgpgoAAg6QAAg4ApgqQAagaAigJQASgFATAAQA6AAAoAoQApAqAAA4QAAA6gpAoQgoApg6AAQgTAAgSgFg");
	this.shape_1.setTransform(18.3,-14.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLAPQAAA6gpAPQgoAQg6AAQg5AAgogQQgpgPAAg6QAAg4ApgeQAogfA5gBQA6gBAoAfQApAgAAA4g");
	this.shape_2.setTransform(18.3,-15.6522);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhhBYQgpgPAAg6QAAg4ApgeQAogfA5gBQA6gBAoAfQApAgAAA4QAAA6gpAPQgoAQg6AAQg5AAgogQg");
	this.shape_3.setTransform(18.3,-15.6522);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLgIQAAA5gvAKQgvAKg2ABQg3ACglgLQglgMAAg5QAAg5AuACQAuACA4gGQA5gFAkAEQAkADAAA5g");
	this.shape_4.setTransform(18.3,-13.2947);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AhlA9QglgMAAg5QAAg5AuACQAuACA4gGQA5gFAkAEQAkADAAA5QAAA5gvAKQgvAKg2ABIgPABQgtAAgggKg");
	this.shape_5.setTransform(18.3,-13.2947);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFCE00").s().p("AgyDiIgGgBIgHgDQgJgHgHgIQgIgJgEgLIgGgRIgEgUIgEgTIgDgUIgGgCIgFgCIgFgEIgEgEIgEgEIgDgFIgDgEIgKgMIgKgLIgJgLIgJgLIgHgKIgEgFIgLgKIgKgLIgJgIIgJgJIgJgLIgEgFIgDgHIgDgGIgCgGIgCgGIAAgGIABgFIABgGIACgFIADgFIADgEIADgEIAEgDIAEgEIAFgCIAFgCIAFAAIAFgBIAGAAIAFABIAFACIAFACIAEAEIAFADIAEAFIAEADIADAFIADAEIADAFIAEAFIAFAFIAFAFIADAFIAEAEIADAFIAEAEIACADQADAAgBgNIAAgXIAAgPIAAgPIAAgNIABgGIADgFIACgGIAEgEIAEgEIAEgDIAFgDIgCgHIgEgNIgCgMIgBgOIABgEIADgKIACgFIACgEIAEgFIAEgDIAEgDIAFgDIAFgBIAFgBIAFAAIAGABIAFAAIAFACIAEACIAFADIAEADIAEAEIAEAEIAEAEIADgFIADgEIAEgEIAFgDIAEgDIAGgCIAFgBIAFAAIAFAAIAFABIAFACIAEADIAFACIAEADIADAFIADADIADAGIADALIAEAOIACAMIABAIIABAGIAAAHIADgCIAEgCIAFgBIAFgBIAGgBIAFABIAFABIAFABIAFACIAFADIAFAFIAFADIAEAFIAFAEIAEAFIAFAFIAFAFIAFgFIAEgEIAFgFIAFgEIAGgDIAFgEIAGgCIAFgCIAGgBIAGAAIAFAAIAGABIAFACIAFACIAFAEIAEADIAEAEQAJAOAFAQIAJAgQAFARACAQQADAQAAAQIAAAjIgBAFIgBAFIgBAFIgCAFIgDAEIgCAFIgDADIgEAEIgFADIgEABIgEACIABAEIADAGIACAHIACAGIABAHIACAGIADAGIADAFIADAGIADAHIADAFIACAGIABAGIABAFIgBAHIgBAGIgDAFIgDAGIgEAEIgEAEIgFADIgEACIgFACIgFABIgFABIgGgBIgFgBIgFgCIgEgCIgFgDIgEgEIgDgDIgCgDIgEgGIgEgFIgDgGIAAgBIABADIgDgFIgDgFIgDgFIgCgFIgCgGIgBgFIgCgGIgEAEIgFAEIgFADIgGAEIgGADIgFACIgGACIgGAEIgFACIAAABIgEAFIgEAFIgFAEIgFAEIgGADIgHACIgGACIgGABIgGACIgGADIgGACIgHABIgHABIgHAAIgHADIgIACIgGADIAAAAIgGAFIgFAEIgGAEIgGAEIgGACIgGABIgHAAIgHAAg");
	this.shape_6.setTransform(13.025,-15.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLgDQAHA4gzAkQgzAkg1gQQg3gQglgYQglgYAAg0QgBg2AlgXQAkgXA5gFQA3gFArAcQAqAdAIA5g");
	this.shape_7.setTransform(18.3477,-13.738);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgJBtQg3gQglgYQglgYAAg0QgBg2AlgXQAkgXA5gFQA3gFArAcQAqAdAIA5QAHA4gzAkQgjAZglAAQgRAAgPgFg");
	this.shape_8.setTransform(18.3477,-13.738);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACLgWQAKBZguAtQguAtg9gCQg+gDglgxQglgxAAg1QAAg1AkgxQAkgxA5gDQA4gEAqAXQAqAXAKBZg");
	this.shape_9.setTransform(18.5161,-14.6059);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgECbQg+gDglgxQglgxAAg1QAAg1AkgxQAkgxA5gDQA4gEAqAXQAqAXAKBZQAKBZguAtQgrArg6AAIgGAAg");
	this.shape_10.setTransform(18.5161,-14.6059);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},6).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},4).to({state:[{t:this.shape_8},{t:this.shape_7}]},1).to({state:[{t:this.shape_10},{t:this.shape_9}]},1).wait(9));

	// eyes
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("AClAAQAABmgxBHQgvBIhFAAQgPAAgOgEQgxgMgmg4QgwhHAAhmQAAhkAwhIQAmg4AxgMQAOgEAPAAQBFAAAvBIQAxBIAABkg");
	this.shape_11.setTransform(17.5,-16.45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgdDxQgxgMgmg4QgwhHAAhmQAAhkAwhJQAmg3AxgMQAOgEAPAAQBFAAAwBHQAwBJAABkQAABmgwBHQgwBIhFAAQgPAAgOgEg");
	this.shape_12.setTransform(17.5,-16.45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("AClgTQAABlgwAyQgwAzhFACQhEADgwg1Qgwg1AAhlQAAhlA1gjQA1giBEAFQBFAGArAdQArAdAABlg");
	this.shape_13.setTransform(17.5,-14.4809);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ah0CHQgwg1AAhlQAAhlA1gjQA1giBEAFQBFAGArAdQArAdAABlQAABlgwAyQgwAzhFACIgFAAQhBAAgugyg");
	this.shape_14.setTransform(17.5,-14.4809);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACegHQASBTgsAPQgrAQhEACQhEADg1gSQg1gSgJhUQgIhVBugKQBtgKAbAJQAbAKATABQATACARBUg");
	this.shape_15.setTransform(16.4349,-13.8659);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhkBeQg1gSgJhUQgIhVBugKQBtgKAbAJQAbAKATABQATACARBUQASBTgsAPQgrAQhEACIgRAAQg6AAgugPg");
	this.shape_16.setTransform(16.4349,-13.8659);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACcAFQAGBVgkA3QgkA2g1APQg1AOhMhFQhMhFAPieQAOigCCAOQCBAOASAuQASAugDAPQgDAOAGBUg");
	this.shape_17.setTransform(17.8393,-15.3066);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhcCfQhMhFAPieQAOigCCAOQCBAOASAuQASAugDAPQgDAOAGBUQAGBVgkA3QgkA2g1APQgKACgKAAQguAAg/g5g");
	this.shape_18.setTransform(17.8393,-15.3066);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#FFFFFF").ss(4,1,1,3,true).p("ACoAPQAGBVgaBVQgaBWhZANQhYAMhAhiQhAhiAUjAQAUjBB+ABQB+ABAeBdQAdBcgDAPQgDAOAGBUg");
	this.shape_19.setTransform(16.6125,-16.3001);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ah3DGQhAhiAUjAQAUjBB+ABQB+ABAeBcQAdBdgDAPQgDAOAGBUQAGBVgaBVQgaBWhZANIgVABQhLAAg4hXg");
	this.shape_20.setTransform(16.6125,-16.3001);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11}]}).to({state:[{t:this.shape_14},{t:this.shape_13}]},6).to({state:[{t:this.shape_16},{t:this.shape_15}]},2).to({state:[{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_16},{t:this.shape_15}]},4).to({state:[{t:this.shape_18},{t:this.shape_17}]},1).to({state:[{t:this.shape_20},{t:this.shape_19}]},1).wait(9));

	// head
	this.instance = new lib.CachedBmp_2();
	this.instance.setTransform(-514.05,-92.25,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-514,-92.2,640.5,467);


(lib.doorhandle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000033").s().p("AjODOQhVhVgBh5QABh4BVhWQBWhVB4AAQB5AABVBVQBXBWAAB4QAAB5hXBVQhVBXh5AAQh4AAhWhXg");
	this.shape.setTransform(-6.75,5.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.doorhandle, new cjs.Rectangle(-36,-23.9,58.5,58.5), null);


(lib.walking = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {walking:0,standing:25};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_24 = function() {
		this.stop();
		
		this.gotoAndPlay("walking");
	}
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(24).call(this.frame_24).wait(5).call(this.frame_29).wait(1));

	// head
	this.instance = new lib.head();
	this.instance.setTransform(-112.05,86.7,0.5973,0.627,0,0,0,-193.8,141.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2).to({y:93.1},0).wait(2).to({y:103.6},0).wait(2).to({y:113.7},0).wait(2).to({y:86.7},0).wait(2).to({y:93.1},0).wait(2).to({y:103.6},0).wait(2).to({y:113.7},0).wait(2).to({y:86.7},0).wait(2).to({y:93.1},0).wait(2).to({y:103.6},0).wait(2).to({y:113.7},0).wait(2).to({y:86.7},0).wait(2).to({y:93.1},0).wait(2).to({y:86.7},0).wait(2));

	// legs
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF6600").s().p("ApFHqIgMAAIgGAAIgFgBIgFgBIgFgCIgFgCIgEgDIgCgBIgCABIgFgBIgGgBIgFgCIgEgCIgFgCIgEgEIgDgEIgDgFIgGgMIgFgOIgFgNIgCgIIgCgIIgCgHIgCgHIgCgGIgDgGIgDgFIgDgGIgCgGIgCgHIgDgFIgCgEIgCgFIgCgFIgBgFIAAgEIgBgFIgBgEIgCgFIgCgHIgCgFIgBgHIgBgGIgBgGIAAgGIAAgHIAAgGIAAgGIAAgGIgDgFIgCgFIgBgGIgCgEIAAgBIgEgFIgEgEIgEgFIgEgEIgEgGIgCgHIgDgGIgCgGIgBgGIgDgGIgDgHIgCgHIgBgFIAAgGIgBgBIgCgGIgCgFIgCgFIgBgIIgBgHIgBgFIAAgGIAAgFIABgFIACgGIACgEIADgFIAEgEIAEgCIAEgEIAFgCIADgBIABgIQACgIADgIIAIgRIAJgSQAFgIAGgGIAFgGQADgKAGgKQAEgJAGgGIALgNIANgNIAHgHQgGgHgEgHIgHgTIgFgMQgDgIgFgGIgHgKIgDgGIgCgHIgCgFIgBgHIgDgGIgCgFIgCgFIgBgEIgDgFIgCgDIgCgFIgBgGIgBgHIgBgHIAAgGIgCgGIgCgHIgCgGIgBgGIgBgIIgBgHIAAgIIgBgIIgEgUIgEgaIgDgUIgEgVQgCgOAAgPIABgFIABgFIABgFIADgFIADgEIADgEIAEgDIAEgDIAFgDIAFgBIAFgBIAFAAIACAAIABgBIAFgDIAEgDIAFgCIAFAAIAdgBIAfAAIAWAAIAXAAIATABIAMABIAGABIAFADIAFAEIAFAAIAGgBIAFgBIAFABIAFABIAFABIAFACIAEADIAEADIAEAFIADADIACAGIACAEIABAGIAAACIABADIABAFIABAFIAAAHIAAAIIAAAHIABAFIACAGIACAGIABAFIADAHIADAIIACAGIACAHIAEAGIADAFIAEAEIACAGIACAFIACAGIACAGIAEAFIAEAGIADAFIAEAFIAFAEIAEAEIAEAFIADAFIADAFIADAFIADAFIAEAGIAFAGIAFADIAEAEIAFAFIAFAEIAEAGIAFAGIADAFIADAFIADAGIACAFIACAHIADAFIADAFIACAGIACAHIABAFIAAAGIAAAEIgBAGIgCAFIgCAEIgDAFIAAAEIAAAMIgCANIgCAKIgEALIgFATIgFATIgDANQgDAJgEAIIgKASIgDAFIgCAGIgCAHIgCAFIgCAHIgCAHIgDAGIgDAGIABgDIgCAFIgDAFIgCAGIgDAFIgCAGIgDAEIgDAFIgEAGIgEAFIAAABIgBAHIgCAGIgCADIABACIAGAMIAGAMIAGAMIABACIAAAAIABABIAAAAIABACIAEADIADAFIADAFIADAFIADAFIAEAFIAEAEIAEAFIAFAGIAEAGIADAFIACAFIADADIALAOIAHALIAJAMIAJALIAIAMIAEAGIAJAKIAFAFIAEAEIAEAFIAEAEIAEAEIADAEIAEAFIADAEIAEACIAEADIAEAEIADADIADAFIADAEIABAFIABAFIABAFIgBAGIgBAFIgBAFIgDAEIgDAFIgDADIgEAEIgEADIgFACIgFACIgFABIgFABIgIAAIgIAAIgHAAIgIAAQgJABgJAEIgTAHQgLADgLABIgXACIgBABIgCAAIgBAAIAAABIgBAAIgBAAIgCABIgHACIgHACIgGAAIgGACIgHAAIgGAAIgHAAIgEABIgEACIgFACIgGAEIgGADIgFABIgHACIgGABIgGABIgHACIgFACIgGACIgNACIgNACIgNABIgLAAgArcDjIABABIgBgCIgBgBIABACgAmshfIAAACIABgCIAAgBgAFTHOIgFgCIgFgBIgFgCIgEgDIgEgEIgEgEIgCgFIgEgCIgDgCIgEgEIgFgEIgEgFIgEgDIgSgLIgKgHIgJgIIgJgJIgKgLQgHgHgIgHIgLgIIgLgJIgMgKIgFgEIgMgIIgFgEIgGgFIgEgEIgEgFIgEgEIgDgDIgIgCIgFgBIgGgDIgGgDIgFgBIgFgBIgGgCIgGgCIgGgDIgFgCIgBgBIgBAAIgFgDIgGgDIgFgBIgGgBIgGgCIgFgDIgEgDIgEgDIgDgEIgFgEIgDgGIgCgFIgCgGIgBgGIgBgFIAAgFIACgFIABgFIADgEIADgFIADgEIAEgEIAEgCIAFgDIACgBIAAgFIABgMIABgOIACgPIABgFIACgFIACgEIAAAAIAAgHIABgHIAAgFIAAgHIABgHIABgGIACgGIACgGIADgGIAAgHIAAgIIAAgIIABgHIAAgHIADgNIACgHIADgFIAAgFIAAgHIAAgGIAAgGIAAgHIABgMIABgHIABgHIABgFIACgGIADgGIAAgMIAAgbIAAgdIAAgpIAAgcIgBgOIgDgFIgCgGIgBgGIgBgGIgBgGIAAgGIAAgGIAAgGIAAgGIAAgHIAAgGIgBgGIgCgEIgCgEIgCgGIgBgGIgBgFIgCgGIgCgFIgCgGIgCgHIgBgIIgCgGIgCgFIgCgGIgCgFIgDgFIgDgEIgCgFIgCgFIgBgGIAAgGIAAgFIABgFIgCgCIgDgEIgCgFIgCgFIgBgFIAAgGIAAgFIABgFIACgFIACgFIADgEIAEgEIADgDIAFgDIAEgDIAFgBIAFgBQALgBAKABIAXAAIAXAAIAYAAIAXAAIAPAAIAFgDIAGgCIAFgCIAGgBIAGAAIAFgBIAGAAIAGAAIAGAAIAFAAIAGABIAFABIAEADIAEADIAEADIAEAEIADAEIACAFIACAFIABAFIADACIADADIAEAEIADAEIACAFIACAEIABAGQABA4gBA5IAABtIAAB2IAABZQABAQgEAQIgCAFIgCAFIgBAKIgBAPIAAAOIAAAKIgBANIgBAHIAAABIABACIABAAIAGAAIAGABIAHACIAGACIAFACIAeADIAdAGIAkAIIATADQAKADAKAEIABABIAGAAIAGABIAGABIAGACIAFADIAGACIAFABIAGABIAFADIAFACIAGACIAFABIAGABIAGADIAFACIAGACIABAAIAIABIAHAAIAHABIAGACIAGABIAFACIAFACQALACAKgBIAWAAIAWAAIATABQAJAAAIACQAIABAHADIAFACIAEAAIAGABIAFABIAFACIAEACIAEADIAEAEIAEADIADAFIACAEIACAFIAAADIACABIAFACIADAEIAEADIADAFIACAEIACAGIABAEIAAAGIAAAFIgBAGIgCAFIgCAEIgDAFIgEADIgDADIgFAEIgEACIgFABIgFABIgNABIgPgBIgHAAIgPABIgOAAIgBAAIgCABIgFACIgGADIgFABIgGAAIgFABIgMAIIgLAGIgKAFIgMAEIgOAEIgEADIgFADIgFACIgGADIgGADIAAAAIgFAEIgGADIgGADIgGACIgGACIgGADIgGADIgGACIgFADIgGADIgHACIgDABIgEACIgFADIgGACIgFABIgGACIgGADIgFADIgGADIgGADIgGACIgGACIgEABIgDACIgHAEIgDACIgEACIgGAEIgGADIgGAEIgGADIgDADIgEAEIgCACIgFAEIgFAEIgGACIgCAAIAAABIgEACIgFABIgFACIgGAAIgFAAgAA3B9IgBACIABgCIAAAAg");
	this.shape.setTransform(-61.8625,274.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6600").s().p("AGvHuIgFAAIgEAAIgGAAIgGgCIgGgCIgFgDIgFgEIgEgFIgEgFIgDgFIgCgGIgDgFIgCgGIgCgGIgEgGIgDgHIgDgGIgCgFIgFgDIgFgEIgFgDIgFgEIgFgDIgFgDIgGgDIgFgDIgFgDIgFgEIgFgEIgIgBIgHgBIgGgCIgFgCIgGgCIgFgDIgHgDIgGgDIgHgDIgEgCIgDgCIgGgEIgEgFIgFgDIgFgEIgFgEIgFgDIgFgFIgGgFIgDgCIgFgDIgEgDIgEgDIgFgDIgFgEIgFgFIgFgFIgFgEIgDgEIgCAAIgFgCIgFgCIgEgDIgEgEIgDgDIgDgFIgDgEIgBgFIgBgFIgBgGIAAgEIAAgEIABgGIAAgGIABgGIABgGIACgFIACgFIADgEIADgEIAEgFIAEgFIAFgEIAEgGIAFgEIAEgEIAEgEIAEgDIAEgCIgBgEIAAgFIAAgFIABgFIACgFIACgFIACgDIABgFIABgFIACgGIADgHIADgGIAEgLIADgMIAEgLIAEgKIAGgKIAGgKIAEgOIAEgNIAEgNIAEgKIAAgIIAAgHIAAgIIAAgHIABgGIABgFIABgEIgBgBIgDgFIgDgFIgCgEIgBgEIgDgEIgDgFIgDgFIgDgGIgFgMIgCgGIgKgOIgIgQIgEgJIgFgKIgEgLIgGgNIgDgEIgCgFIgCgGIgDgGIgCgEIgDgEIgCgFIgBgHIgBgHIgBgHIAAgBIgDgFIgCgFIgCgGIgBgGIgBgEIgBgFIgEgOIgFgOIgEgNIgDgMIgBgFIgCgDIgDgEIgEgEIgEgFIgCgFIgCgEIgDgGIgEgHIgEgGIgHgLIgGgKIgGgLIgEgLIgCgGIAAAAIgBgBIgBgFIAAgFIAAgBIAAgFIABgFIACgFIADgFIAAAAIACgEIAEgEIAEgDIAEgDIAEgCIABgBIAFgBIAFgBIAFgBIABAAIAGAAIAHAAIAHAAIAIABIAHgBIAEgCIAEgCIAFgCIAHgCIANAAIAMgBIATABIALABIALADIAHACIADABIACgCIADgDIAEgEIAEgDIAFgCIAFgCIAFgBIAFAAIAGAAIAFABIAEACIAFACIAEADIAEADIADAEIADAEIACADIADACIAEADIAEADIADAEIADAEIADAFIABAFIABAFIABAFIABACIADAFIAEAFIAEAGIAEAFIADAFIAEAGIADAFIADAGIAFAEIAFAFIAEAGIAEAGIACADIAFAFIAEAFIAFAFIAFAGIAFAHIACAEIADAGIAFAGIAFAHIAFAJIADAFIAGAMIAFAFIADAFIAEAGIADAFIAEAGIAEAFIAFAFIAEAEIADAFIADAFIAEAFIAEAEIAHAKIADAEIAEAJIADAEIADAFIADAFIAEAFIADAFIADAFIADAFIADADIADAEIADAEIACACIAFAFIAEAGIADAGIABAFIADAFIADAFIACAFIACAFIABAFIABAFIgBAGIgBAFIgBAEIABAEIABAFIABAGIAAAGIAAAGIAAAHIAAAGIAAAHIgBAOIgBAJIgBAGIgCAEIgCAFIgBACIgBAFIAAAFIgBAHIAAAGIgCAHIgBAGIgCAGIgDAGIAAABIAAAFIgBAGIAAAFIAAAFIgBAFIgCAFIgCAFIgCAFIgCADIgBAFIAAAFIgCAFIgCAGIgEAFIgBAGIgBAGIgBAGIgDAGIgCAFIgCAGIADABIAGAFIAGAEIAFACIAEACIAJAFIAFADIAFACIAIAFIAFACIAFACIAFADIAEADIAJAIIAFAEIAFAFIAGAEIAFADIAIAIIAEADIAEAEIALAJIAPAMIAJAJIAEAEIAGAEIAFAFIAKAIIADADIAFADIAEAEIAFACIAEACIADACIADADIAGACIAGADIAEACIAFABIAGADIAGADIAFAEIACABIAEADIAEADIAEADIADAEIADAEIADAFIABAFIABAFIABAFIgBAGIgBAFIgBAFIgDAEIgDAFIgDADIgEAEIgEADIgFACIgFACIgFABIgMAAIgOAAIgOAAIgPAAIgPAAIgHAFIgGAEIgGADIgGACIgGACIgHACIgcANIgbALIgaALIgRAGIgKAEIgFADIgFADIgGADIgGADIgOAFIgIAFIgEADIgFADIgEADIgFADIgGACIgFABIgGAAIgGABIgGAAIgBAAgAGClqIABABIgBgCIgBgBIABACgAEUl6IABABIgCgDIgBgCIACAEgAnrFbIgGgCIgGgCIgGgDIgFgEIgEgGIgEgGIgEgFIgFgGIgDgFIgEgFIgEgEIgHgEIgEgDIgFgDIgEgEIgFgEIgEgEIgFgEIgFgEIgQgLIgQgLIgQgLQgJgIgIgKIgJgPIgKgRIgDgFIgEgEIgEgEIgEgFIgFgGIgFgGIgCgFIgDgFIgCgCIgBgCIgHgDIgEgDIgEgDIgFgEIgFgEIgFgEIgFgFIgGgEIgEgDIgEgEIgEgDIgEgEIgFgEIgDgGIgDgFIgCgFIgCgGIgBgGIgBgFIAAgFIAAAAIgBgGIAAgOIAAgPIAAgOIAAgNIABgPIACgPIABgHIACgHIACgGIABgBIAAgIIABgHIABgIIACgFIACgGIACgFIABgCIAAgGIAAgHIAAgGIAAgHIABgHIABgHIABgGIACgGIACgGIACgGIACgHIABgGIAEgFIAEgFIAEgFIAFgDIAGgDIAGgCIAGAAIAHAAIABAAQAugSAzAFQAfACAeAAIBlAAIBYAAIAUAAIAAAAIgEgFIgDgFIgEgGIgCgFIgCgFIgCgGIgDgEIgDgFIgCgFIgCgHIgBgGIgDgGIgDgGIgCgFIgCgEIgFgOIgDgHIgCgFIgDgFIgDgEIgDgEIgDgFIgCgHIgBgGIgEgFIgEgFIgEgFIgDgGIgGgLIgDgFIgDgEIgDgEIgDgFIgBgFIgCgFIgBgFIAAgFIAAgFIAAgFIAAgFIABgFIACgFIACgFIADgEIAEgEIADgDIAFgDIAEgDIAFgBIAFgBIAGgBIAFABIAFABIACgCIAEgDIAFgDIAFgBIAFgBIALgBIAMAAIAGAAIAHAAIAGAAIAGABIAGAAIAGABIAGACIAFACIAGADIAPAAIAQAAIAIAAIAGAAIAFAAIAGAAIAFAAIAJAAIABgCIAEgEIADgDIAFgDIAEgDIAFgBIAFgBIAGgBIAFABIAFABIAFABIAFADIAEADIAEADIADAEIADAEIADAFIABAFIABAFIABAFIAAAHIAAAGIACAEIgBgBIABABIAAABIAAgBIAAACIAAAAIABABIACAGIADAHIACAGIADAHIADAFIADAFIACAFIACAEIADAFIADAFIACAFIACAHIACAGIADAFIACAGIACAGIABAHIABAHIADAFIACAGIADAHIACAHIACAGIADAFIACAGIgCgFIgCgFIAIASIAIAOIAJASIAHAOIAKAUIAFANIADAHIADAEIACAFIACAEIACAHIACAHIACAFIADAGIACAFIgCgFIgCgEIADAFIADAFIADAGIADAFIABAGIABAFIABAGIACABIADAFIABAEIACAFIABAFIAAAGIAAAFIgBAFIgCAFIgBAFIgDAEIgDAEIgEADIgFADIgEACIgEADIgFADIgFACIgHABIgHACIgEACIgFACIgFACIgGACIgHACIgGAAIgHABIAAAAIgGACIgFACIgFACIgIABIgHABIgFABIgFACIgFACIgGACIgGACIgHAEIgGACIgEABIgEABIgEADIgFABQgIADgIABQgJACgJAAIgRABIgXAAIgUAAIgGAAIgBAAIgGACIgHADIgGABIgHACIgGAAIgGABIgHAAIgBAAIgFADIgGACIgGABIgFABIgGABIgGAAIgIABIgIAAIgEACIgGADIgGACIgHABIgHABIgEAAIgBAAIAAADIAAATIgBAVIgEAWIgCAGIgCAGQgBATAAATIAAAlQAAAWgGAVQgEAOgFANIgCAHIgBABIAAAHIgBAIIgBAHIgBAHIgCAHIgDAGIgCAFIAAABIgBAFIgBAFIgDAEIgCAFIgEAEIgFAEIgFADIgGACIgGACIgGAAIgGAAgAmiB0IAAACIABgCIAAgBgAk+AQIABAAIACAAIgCAAIgBAAgAr8g+IAAABIABgBIAAgCIgBACg");
	this.shape_1.setTransform(-72.425,275.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF9933").s().p("AD6HuIgOAAIgOAAIgNAAIgOAAIgMgBIgGgBIgFAAIgGgBIgGgCIgLgGIgLgGIgLgHIgFgEIgGgEIgEgEIgGgEQgJgHgLgEIgSgHIgSgHIgRgHQgNgFgOgHIgLgHIgGgBIgGgBIgGgCIgHgCIgHgDIgFgCIgFgDIgEgDIgFgEIgDgFIgEgFIgCgGIgCgGIAAgGIAAgDIgBgCIAAgFIAAgFIABgFIABgFIADgFIADgEIADgFIAAAAIADgEIAEgFIACgEIAEgFIADgFIADgFIAEgFIAEgSIAGgTIAGgTQAGgMAHgMIABgGIADgHIACgHIADgDIACgDIADgFIADgFIACgOIADgOIAFgNIADgMIAEgMIACgGIAAgGIAAgGIACgGIACgFIADgFIACgEIAEgFIADgFIAAgBIgEgDIgFgFIgGgEIgDgEIgEgFIgDgEIgDgFIgFgEIgDgEIgEgEIgDgFIgEgEIgDgFIgDgGIgEgEIgDgEIgDgFIgDgFIgDgEIgCgEIgBgBIgBgCIgBgBIAAABIgCgDIgCgEIgEgEIgDgFQgSgVgUgUIgRgPQgfgagigWQgigUgkgPQgegMgcgRIgRgLIgUgQQgSgMgUgKIgmgSQgSgKgRgLIgggYIgVgPIgFgCIgFgCIgEgDIgFgDIgDgEIgDgFIgDgEIgBgEIgEgGIgCAAIgEgDIgEgDIgDgEIgDgFIgCgFIgCgEIgBgGIgBgHIABgGIADgGIACgGIADgEIAEgEIADgEIAEgCIAFgDIAFgBIAGgCIAHAAIAGABIAFACIAHADIAGACIAEAEIAGAEIAFgEIAGgDIAHgEIAEgDIAFgEQAOgIAQgGQARgHATgCQASgCASAAIAbABIAIAAIAAgBIAEgDIAFgCIAFgCIAFgBIAGAAIAGAAIAGABQARAFAPAKIARAMIAVATIATASIAGAEIAEAEIAFAEIAEAEIAFAEIAEAFIAEADIABABIADAFIAGAEIAEAFIAFAEIADADIADAEIADAFIAFAEIADACQAbAEAZAIQAZAIAXAMQAYANAVASQALAKAIAMIADAEIAFADIADAEIACABIALAGIAMAIIALAIIARANQAJAJALAGIAKAGIAHADIAGACIAGADIAGADIAGAEIAFAFIAGAEIAGAFIAEADIAFADIAEADIAFADIAEADIACACIAAAAIAAAAIAAAAIABABIAEACIADACIAFACIAEADIAEADIAEAFIAFAEIAEAFIAEAFIAEAFIADAFIAEAFIAGALIAEAEIADAFIAEAFIAEAFIAFAFIAEAFIAFAEIADAEIADAFIACAEIACAFIABAFIAAABIACACIAEAFIADAEIADACIAEACIAEABIAFABIAFADIAEACIAEAEIAEAEIADAEIACAFIABAFIABAFIABAEIgBAFIgBAFIgBAFIgCAFIgDAEIgDAEIgIAVIgFAMIgGALQgEAJgGAHIgGAIIgGAIIgDAEIgDAFIgDAGIgEAFIgDAFIgDAEIgDAEIgBAEIgBAEIgCAGIgEAGIgBAGIgBAFIgCAGIgCAFIgDAGIAAABIAAAFIgBAEIAAADIASAGIAYAKIAGACIADAAIACABIAAAAIABAAIABAAIgBAAIADAAIAHABIAHABIAGABIAMAFQAJACAIADIAHACIAFADIADABIAFACIAGADIAFADIAQAFIANAGIALAFIAJAFIAKAEIAEADQAKAAAKADIAFABIAGACIAFADIAGACIAEADIAEADIABABIADADIAEAEIADAEIACAFIACAFIABAFIABAFIgBAGIgBAFIgCAFIgCAEIgDAFIgEADIgDAEIgEADIgFACIgFACIgFABIgMAAIgPAAIgOAAIgNAAIgHACIgFABIgGACIgGACIgEACIgGADIgFACIgGABIgGACIgFAEIgGAFIgFAEIgGAEIgGAFIgFAEIgGAEIgGAFIgEAEIgGAFIgDAFIgDAFIgEAEIgEAFIgFAFIgEAEIgFADIgGAEIgEADIgCAEIgBADIgFAFIgDAFIgGADIgEADIgGACIgCABIgBABIgFABIgGABIgNABIgGAAg");
	this.shape_2.setTransform(-61.2,276.6083);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF6600").s().p("AikISIgGAAIgHgCIgHgCQgQgJgNgKIgXgTIgYgUIgYgTIgbgVIgOgMIgEgEIgFgCIgFgFIgGgEIgFgFIgGgEIgFgFIgEgEIgFgFIgFgEIgGgEIgHgEIgFgBIgHgCIgGgBIgEgEIgGgDIgFgEIgFgEIgDgEIgDgEIgEgDIgDgEIgDgEIgEgGIgDgFIgDgEIgDgEIgBgFIgBgBIgOAGIgHABIgGABIgGgBIgEgBIgGgBIgFgDIgEgDIgDgDIgEgEIgCgEIgDgFIgCgFIAAgCIgCgEIAAgGIAAgFIABgFIACgFIADgFIACgEIAEgEIAEgDIAEgEIAFgCIAEgBIAHgBIAqgbIAigYQARgMATgJIAegOQAGgCAIgCIAEgEIAEgEIAFgDIAEgEIAFgDIAWgVQAMgMAOgLQALgJAJgKIAPgSIAEgDIAEgDIADgEIAEgFIAFgEIADgFIADgDIAEgEIAEgDIAFgCIAFgCIADAAIABgDIADgEIACgEIADgEIADgGIADgGIADgEIAEgEIADgDIAFgDIACgFIADgFIAEgDIADgFIAGgEIAFgEIAGgDIAGgEIADgDIAFgDIAEgEIAHgNIAGgOIAGgLIAHgMIACgFIADgFIAFgGIAEgFIAEgGIADgGIADgEIADgFIADgDIADgEIADgFIADgGIAEgFIAEgFIAEgGIAEgFIAEgGIAEgGIADgGIAEgGQAHgTALgPIARALQAcAQAeANQAkAPAiAUQAiAWAfAaIARAPIgCADQgJAPgNANIgHAHIgLARIgMARIgJAMIgJALIgGAIIgCACIgTAYIgTASQgMANgKAOIgUAeIgKAQIgIATIgIAQIgEAJIgGALIgFAKIgGAJIgDAGIgIAJIgEAFIAFAGIACAFIACAEIABAEIADADIABABIABABIACAEIAFAGIADAFIADAGIAEADIADADIAIAIIAHAKIAIALIADAFIADAGIAEAEIAJAJIADAFIAFAEIAKAKIAEAGIAGAEIALAGIAMAHIARAJIANAGIAHAEIAFADIAEAAIAFABIAFACIAEADIAFACIADAEIAEAEIADAEIACAFIACAFIABAEIAAAGIAAAFIgBAGIgCAEIgCAFIgDAEIgEAEIgDADIgFAEIgEACIgFACIgFAAQgRACgSgBIgsAAIgjAAIghAAIgSAAIgGABIgGACIgGACIgGABIgFABIgGABIgGACIgGAEIgGADIgFAEIgHAEIgGADIgFAFIgHADIgDAFIgEAEIgDAEIgFADIgDACIgFAFIgFADIgGAEIgFADIgGACIgFADIgFADIgHADIgHADIgFADIgDADIgEAEIgFADIgEACIgFABIgEABIgGAAgAhZAFIgCABIACAAIABgBIgBAAgAF+kvIgDgEIgFgDIgDgFQgIgMgLgJQgVgSgZgNQgXgMgZgIQgZgIgbgEIgDgCIgFgFIgDgEIgDgEIgDgDIgFgFIgEgEIgGgFIgDgEIgBgBIAKgJIAYgWQAMgKANgJQAGgDAGgCIAAgBIACgFIADgGIACgEIAEgDIAEgEIAFgCIAEgCIAFgDIAFgBIAFAAIAFAAIAGABIADACIAGABIAHABIAFACIAGABIAFACIAFAAIAHAAIAFAAIAAAAIAFgDIAGgCIAFgBIAHgCIAHgBIAGAAIAHAAIABgBIAGgCIAGgCIANgCIANgCIAOAAIAVAAIAOAAIALABIAGABIAEACIAFACIAEADIAEAEIADADIADAFIADAEIACAFIAAAFIABAGIgBAFIAAAFIABABIADAFIADAEIACAGIABAEIAAAGIAAAGIgBAFQgEARgMANIgTAVQgOAPgQANIgiAZIgYASIgFAEIgFAFIgFAEIgDAFIgCgBg");
	this.shape_3.setTransform(-92.6,280.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF9933").s().p("AJSGAIgFgBIgFgCIgFgCIgEgDIgCgCIgLABIgMAAIgNgBIgNgBIgMgCIgLgEIgFgCIgEgDIgEgDIgBgBIgFgDIgEgCIgEgDIgEgDIgEAAIgGAAIgGgBIgHAAIgGgBIgGgBIgFgCIgFgCIgEgBIgDgBIgHAAIgHAAIgGgBIgHAAIgGgBIgHgBIgFgCIgFgCIgFgCIgGAAIgMAAIgLAAIgLAAIgMgBIgLgDQgIgCgHgDIgBAAIgFgBIgFAAIgGAAIgGgBIgGgBIgGgBIgFgBIgGgCIgFgDIgCAAIgFgBIgEAAIgEgBIgGgCIgFgCIgGgDIAAAAIgHAAIgHgBIgGgBIgGgDIgFgCIgFgCIgEgCIgBgBIgFgCIgEgCIgFgCIgBAAIgGgCIgGgBIgGgCIgGgDIgFgEIgFgBIgEgCIgFgDIgFgEIgFgEIgEgDIgFgEIgEgEIgDgFIgEgEIgDgFIgDgFIgCgGIgBgFIAAgGIAAgGIgCgCIgEgEIgDgEIgDgFIgDgCIgFgFIgCgDIgDgCIgDgEIgDgEIgCgEIgGgEIgFgEIgGgEIgGgDIgFgCIgDgDIgFgDIgKgHIgEgEIgGgEIgGgEIgFgCIgFgCIgFgCIgEgEIgEgDIgEgDIgBAAIgFgEIgFgDIgFgEIgFgEIgFgFIgDgGIgDgFIgCgEIgCgDIgFgFIgEgFIgCgDIgCgEQgGgFgHgDIgWgNQgNgGgMgIIgSgMIgNgHIgJgCIgOgFIgMgEIgRgIQgIgEgGgFIgHgCIgHgDIgHgDIgFgCIgFgDIgFgDIgFgCIgHgDIgGgDIgGgDIgGgDIgFgEIgLgIIgDgEQgKgCgJgFIgZgMIgCgBIgTgJIgPgKQgHgGgIgEIgDgCIgGgCIgMgEIgGgCIgFgCIgGgDIgKgHIgKgHIgGgDIgFgDIgFgDIgGgDIgGgFIgGgEIgEgEIgEgEIgFgEIgEgFIgFgEIgMgGIgJgEIgLgGIgNgHQgIgEgIgCIgFgDIgEgDIgEgDIgBgBIgEgCIgDgDIgFgDIgEgEIgEgEIgFgEIgEgFIgFgEIgEgFIgGgFIgFgCIgFgDIgFgDIgFgCIgFgEIgGgEIgEgFIgEgEIgDgEIgCgFIgCgFIgBgFIAAgFIAAgFIABgFIACgFIACgFIADgEIADgEIAFgEIAEgCIAFgDIAEgBIAGgBIAFgBIACAAIABAAIAEgDIAFgDIAFgBIAFgBQAOgBAOAAIAeAAIAeAAIAfAAIAmAAIAJAAIACAAIAFAAIABAAIALgEQAKgDAKgBIAAAAIAHAAIAggBIACAAIApAAIA6AAIADAAIA0ABIAFABIAFABIAEADIAFADIABABIAFABIAFAAIAHADIAHACIAGAEIAJAGIAEAEIAEADIAFAEIAEAFIAEAGIAFAGIADAFIACAEIAKALIAEAFIAFAFIAFAFIAEAFIAEAGIADAEIACAGIAEADIAKAGIAFAEIAEADIAJAIIAKAJIAFAFIAEADIAFACIAEADIAEADIAFAEIACABIAEAEIAFADIAFAEIAFAEIAGAEIAFAEIAFADIAEAEIAKAFIAJAGIAIAIIAJAJIAJAIIADACIACABIAFADIAFADIAFAFIAGAEIAFAFIAGAFIAEACIAFADIAFADIAFADIAGACIAFADIAFABIAEABIAFACIAFADIAFACIAEADIAFADIAFAEIAFADIAFACIAFACIADACIAGABIAGACIAFACIAFADIAEADIAFACIAFACIAFACIADADIAEADIAFADIAFADIABAAIAFABIAEABIAFACIAEACIAEACIACAAIAAAAIAFgDIAEgDIAFgBIAFgBIAGgBIACAAIAFgBIAFgCIAFgCIAGgBIAFgCIAHgDIAHgCIAHgCIAGgCIAGAAIAGgBIAFgDIAGgCIAEgBIAEgBIADgCIAFgCIAGgCIAFgCIAGgBIAFgBIAFgBIAFAAIAEAAIAGgDIAGgCIAHgCIAGgCIAHgCIAIgCIAGgDQANgBANgEQAPgEAPgCQAOgBAOAAIAeAAIAOAAIABAAIAGgCIAHgDIAGgBIAHgCIAGAAIAHgBIAGAAIANgDIAMgDIAPgCIAPgBIACgBIAGgCIAFgCIAGgBIAFgCIAFAAIAFAAIAFABIAFACIAFACIAEADIAEADIAEAEIADAFIACAEIACAFIABAGIAAAFIAAAFIgBAFIgCAFIgCAFIgDAEIgDAEIgEADIgEADIgFADIgFABIgDABIAAADIgBAFIgCAFIgCAGIgCAEIgDAFIAAACIgDAHIgDAGIgDAFIgEAFIgFADIgDADIgDADIgDADIgDAEIgDAGIgDAFIgBACIgCAHIgDAGIgEAFIgEAGIgDAFIAAAIIAAAHIAAAIIAAAHIAAAIIABACIACAFIACAFIACAGIABAGIABANIAAANIAAALIAAAGIABABIACADIACAFIACAEIABAFIACAFIABAFIAAAAIACAFIACAFIABAFIABAFIAAAFIABAIIAAAHIgBAOIgDALIgEAMIgDAFIgEAFIgDAEIAAAPIAAAPIAAAOIAAAPIAAAOIAAAGIgBAFIgCAFIgCAEIgDAFIgEADIgDAEIgFADIgEACIgFACIgFABIgGAAIgFAAgAIwCAIABACIAAgCIgBgBIAAABgABMBSIACAAIgCgBIgCAAIACABgAj6kkIABAAIgBgBIAAAAg");
	this.shape_4.setTransform(-49.775,265.5917);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF6600").s().p("AjLHQIgGgBIgEgBIgGgDIgEgDIgDgDIgJgEIgMgGIgLgGIgKgHIgOgHIgMgIIgMgIIgMgIIgKgJIgKgIIgNgIIgNgHIgLgHIgKgIIgKgJIgKgKIgGgEIgGgEIgGgDIgGgDIgHgDIgFgEIgGgCIgHgCIgFgDIgGgDIgGgDIgFgDIgGgDIgEgDIgGgCIgGgFIgFgEIgFgFIgEgGIgEgDIgDgEIgGgFIgGgEIgFgFIgDAAIgFgCIgEgCIgFgDIgDgEIgEgDIgDgFIgCgEIgCgFIgBgFIgBgGIAAgHIAAgIIABgGIACgGIACgGIADgFIADgGIADgGIADgFIAEgGIADgFIAEgFIADgEIACgEIADgDIADgEIABgCIACgHIADgFIABgHIAAgIIAAgPIAAgOIAAgPIABgFIABgGIAAgCIAAgEIAAgFIAAgGIABgFIABgFIADgFIAEgFIADgDIADgEIAFgDIACgBIAFgEIACgDIACgEIADgFIAEgEIABgBIABgFIAEgHIADgGQAFgNAGgKIAKgPIANgOIANgOIAOgOIAJgJIAIgLIADgGIAEgFIAFgGIAZAMQAIAEALACIADAFIAKAHIAGAEIAGAEIAGADIAGACIAHADIAEADIAGADIAEACIAGADIAHADIAHADIAGACQAHAFAIADIARAIIAMAFIAOAEIAJADIANAIIASALQAMAIANAHIAWAMQAHAEAGAFIACADIACAEIAEAFIAEAEIACADIADADIADAGIADAFIAFAFIAEAEIAGAEIAEAEIAFADIACABIgQgEQgWgGgXgHQgRgGgRgHIAAABIgDAFIgDAFIADAEIADAFIACAFIAEAEIAFADIADAEIAFAEIAEAFIAFAFIAEAEQAOAKAMAMQAIAGAIAFIAOALIAPANIAQAPIAKALIACABIACAAQALAFAJAGIAKAGIAJAIIAJAHIAKAHIAKAIIAGAEIAGAEIAGADIAHAEIAQAHIAMAGIAKAGIAKAFIAJAEIAJAFIAEACIAFABIAHACIAFACIAFADIAGAEIADABIAFACIAEADIADAEIAEADIADAFIACAEIACAFIABAFIABAGIgBAFIgBAFIgCAFIgCAFIgDAEIgEAEIgDADIgEADIgFADIgFABIgFABQgZABgaAAIg8AAIg6AAIgxAAIgHAAIgMAIIgMAIIgKAJIgNALIgPALIgKAHIgBACIgCADIgCAEIgEAGIgEAFIgEAEIgDAFIgDAFIgDAFIgDAEIgEAEIgDAFIgCAEIgDAFIgDAEIgDAEIgEADIgEADIgFACIgEABIgFABIgFABIgFgBgAoWD5IgBgBIAAAAgAI5A5IAAgCIABACIAAABIgBgBgAAdjgIgJgJIgJgIIgJgIIgIgGIgKgGIgFgDIgEgEIgGgEIgFgEIgFgEIgFgEIgFgDIgFgDIgCgCIgEgDIgEgDIgEgEIgFgCIgEgCIgFgFIgKgJIgJgIIgEgEIgFgDIgLgHIgDgDIgDgFIgCgFIgEgFIgFgGIgEgFIgFgFIgEgFIgKgKIgDgFIgCgFIgFgGIgEgGIgFgEIAEgDIAFgEIAGgFIAFgCIAFgCIAGgCIAFgBIAGAAIAGAAIAFAAIAGABIAEACIAFACIACgBIAHgCIAGgBIAGABIAGABIAFABIAEADIAFACIARAAIAYAAIAYAAIAWAAIAQAAIAEgDIAFgCIAFgCIAGgCIAIgCIAFgCIAFgCIAFgBIAFgBIAGgBIAEgDIAEgCIAEgBIAGgCIAFgBIAFAAIAGAAIADAAIAGAAIAEABIAGACIAEACIAFADIAEADIAEAFIACAEIACAFIACAFIABAFIABAFIgBAFIgBAFIgCAFIgCAFIgCAEIgFAEIgDAEIgFAEIgDAGIgDAFIgBAGIgCAGIgCAGIgDAHIgEAFIgEAFIgFAGIgEAGIgFAFIgFAKIgDAEIgDAFIgIAJIgEAEIgKAIIgFAFIgEAGIgFAFIgEAFIgFAFIgEAIIgGAJIgIAJIgCgBgAjxlsIAAAAIAAAAIABABIgBgBgAnlm9IAFgBIgBABIgEAAgAnRnDIAHgBIAHgBIADAAQgLABgJADIADgCgAm8nGIADAAIgHABIAEgBgAlunGIgqAAIABgBIAFgDIAEgDIAFgBIAGgBQAcgDAdAGQALACALAEIg6AAg");
	this.shape_5.setTransform(-50.65,272.7109);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_3},{t:this.shape_2}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_3},{t:this.shape_2}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_3},{t:this.shape_2}]},2).to({state:[{t:this.shape_5},{t:this.shape_4}]},2).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape}]},2).wait(2));
	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},2).wait(6).to({_off:false},0).to({_off:true},2).wait(6).to({_off:false},0).to({_off:true},2).wait(6).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-303.3,-59.6,382.6,392.90000000000003);


(lib.rockettween = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_18 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(18).call(this.frame_18).wait(1));

	// Layer_1
	this.rocket_mc = new lib.Symbol1();
	this.rocket_mc.name = "rocket_mc";
	this.rocket_mc.setTransform(89.8,103.4,0.5843,0.5201,0,0,0,153.6,198.7);

	this.timeline.addTween(cjs.Tween.get(this.rocket_mc).wait(1).to({regX:154,regY:283.4,x:90.25,y:44.1},0).wait(1).to({x:88.9,y:-181.9},0).wait(1).to({x:87.5,y:-407.9},0).wait(1).to({x:91.2,y:-520.35},0).wait(1).to({x:94.45,y:-604.7},0).wait(1).to({x:97.75,y:-689.05},0).wait(1).to({x:102.7,y:-771.6},0).wait(1).to({x:107.7,y:-809.75},0).wait(1).to({x:112.75,y:-847.85},0).wait(1).to({x:107.75,y:-960.45},0).wait(1).to({y:-1110.4},0).wait(1).to({x:107.7,y:-1241.8},0).wait(1).to({x:102.75,y:-1369.35},0).wait(1).to({x:102.7,y:-1529.4},0).wait(1).to({y:-1702.1},0).wait(1).to({x:102.75,y:-1902.2},0).wait(1).to({x:112.75,y:-2053.5},0).wait(1).to({x:117.75,y:-2152.35},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.4,-2300.7,212.20000000000002,2595.7999999999997);


(lib.drink = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_18 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(18).call(this.frame_18).wait(1));

	// Layer_1
	this.drink_mc = new lib.Symbol3();
	this.drink_mc.name = "drink_mc";
	this.drink_mc.setTransform(70.5,145.5,1,1,0,0,0,70.5,145.5);

	this.timeline.addTween(cjs.Tween.get(this.drink_mc).wait(1).to({rotation:2.8451,x:137.2},0).wait(1).to({rotation:5.6902,y:145.55},0).wait(1).to({rotation:-1.8096,x:137.15,y:145.45},0).wait(1).to({rotation:-9.3094,y:145.5},0).wait(1).to({rotation:-1.8101,y:145.45},0).wait(1).to({rotation:5.6893,x:137.2,y:145.55},0).wait(1).to({rotation:-1.8105,x:137.15,y:145.45},0).wait(1).to({rotation:-9.3103,y:145.5},0).wait(1).to({rotation:0.7944,x:137.2,y:145.55},0).wait(1).to({rotation:10.899},0).wait(1).to({rotation:3.3994,x:137.15},0).wait(1).to({rotation:-4.1003,y:145.5},0).wait(1).to({rotation:3.3998,y:145.55},0).wait(1).to({rotation:10.8998,x:137.2},0).wait(1).to({rotation:3.4002},0).wait(1).to({rotation:-4.0994,x:137.15,y:145.5},0).wait(1).to({rotation:-1.3758,x:137.2,y:145.45},0).wait(1).to({rotation:1.3479,y:145.5},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3,-4,219.3,304.6);


(lib.birds = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Symbol4();
	this.instance.setTransform(68.2,53,1,1,0,0,0,68.2,53);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:68.3,x:88.6},0).wait(1).to({x:108.95},0).wait(1).to({x:129.3},0).wait(1).to({x:137.9},0).wait(1).to({x:146.5},0).wait(1).to({x:155.1},0).wait(1).to({x:163.7},0).wait(1).to({x:172.3},0).wait(1).to({x:185.9},0).wait(1).to({x:199.5},0).wait(1).to({x:213.1},0).wait(1).to({x:226.7},0).wait(1).to({x:240.3},0).wait(1).to({x:254.9},0).wait(1).to({x:269.5},0).wait(1).to({x:284.1},0).wait(1).to({x:298.7},0).wait(1).to({x:313.3},0).wait(1).to({x:329.1},0).wait(1).to({x:344.9},0).wait(1).to({x:360.7},0).wait(1).to({x:376.5},0).wait(1).to({x:392.3},0).wait(1).to({x:413.1},0).wait(1).to({x:433.9},0).wait(1).to({x:454.7},0).wait(1).to({x:475.5},0).wait(1).to({x:496.3},0).wait(1).to({x:513.5},0).wait(1).to({x:530.75},0).wait(1).to({x:548},0).wait(1).to({x:565.25},0).wait(1).to({x:580.25},0).wait(1).to({x:595.25},0).wait(1).to({x:610.25},0).wait(1).to({x:625.25},0).wait(1).to({x:640.25},0).wait(1).to({x:654.85},0).wait(1).to({x:669.45},0).wait(1).to({x:684.05},0).wait(1).to({x:698.65},0).wait(1).to({x:713.25},0).wait(1).to({x:725.85},0).wait(1).to({x:738.45},0).wait(1).to({x:751.05},0).wait(1).to({x:763.65},0).wait(1).to({x:776.25},0).wait(1).to({x:786.35,y:51.45},0).wait(1).to({x:796.5,y:49.9},0).wait(1).to({x:806.65,y:48.3},0).wait(1).to({x:816.8,y:46.75},0).wait(1).to({x:826.95,y:45.15},0).wait(1).to({x:837.1,y:43.6},0).wait(1).to({x:847.25,y:42},0).wait(1).to({x:858.75},0).wait(1).to({x:870.25},0).wait(1).to({x:881.75},0).wait(1).to({x:893.25},0).wait(1).to({x:906.85},0).wait(1).to({x:920.45},0).wait(1).to({x:934.05},0).wait(1).to({x:947.65},0).wait(1).to({x:961.25},0).wait(1).to({x:976.4,y:37.4},0).wait(1).to({x:991.6,y:32.8},0).wait(1).to({x:1006.8,y:28.2},0).wait(1).to({x:1022,y:23.6},0).wait(1).to({x:1037.2,y:19},0).wait(1).to({x:1057,y:12.8},0).wait(1).to({x:1076.8,y:6.6},0).wait(1).to({x:1096.6,y:0.4},0).wait(1).to({x:1116.4,y:-5.8},0).wait(1).to({x:1136.2,y:-12},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-65,1204.5,171);


(lib.ball = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(19).call(this.frame_19).wait(1));

	// Layer_1
	this.ball_mc = new lib.Symbol2();
	this.ball_mc.name = "ball_mc";
	this.ball_mc.setTransform(129.8,129.8,1,1,0,0,0,129.8,129.8);

	this.timeline.addTween(cjs.Tween.get(this.ball_mc).wait(1).to({x:155.2,y:90.1},0).wait(1).to({x:193.3,y:58.35},0).wait(1).to({x:247.25,y:5.95},0).wait(1).to({x:293.3,y:-28.95},0).wait(1).to({x:337.75,y:-3.55},0).wait(1).to({x:377.45,y:34.55},0).wait(1).to({x:406,y:74.25},0).wait(1).to({x:440.95,y:112.35},0).wait(1).to({x:479.05,y:86.95},0).wait(1).to({x:533.05,y:52.05},0).wait(1).to({x:582.25,y:20.3},0).wait(1).to({x:631.5,y:-17.8},0).wait(1).to({x:679.15},0).wait(1).to({x:706.15,y:25.05},0).wait(1).to({x:728.35,y:61.55},0).wait(1).to({x:763.25,y:88.5},0).wait(1).to({x:788.65,y:129.8},0).wait(1).to({x:822,y:94.9},0).wait(1).to({x:885.5,y:115.55},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-158.7,1015.3,418.3);


(lib.background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// drink
	this.drink_mc = new lib.drink();
	this.drink_mc.name = "drink_mc";
	this.drink_mc.setTransform(2380.15,-564,1,1,0,0,0,70.5,145.5);

	this.timeline.addTween(cjs.Tween.get(this.drink_mc).wait(1));

	// ball
	this.ball_mc = new lib.ball();
	this.ball_mc.name = "ball_mc";
	this.ball_mc.setTransform(4197.75,-127.75,1,1,0,0,0,129.8,129.8);

	this.timeline.addTween(cjs.Tween.get(this.ball_mc).wait(1));

	// rocket
	this.rocket_mc = new lib.rockettween();
	this.rocket_mc.name = "rocket_mc";
	this.rocket_mc.setTransform(630.8,-1122,1,1,0,0,0,346.3,-829.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(4,1,1,3,true).p("EnkGh6IMPINAAAMAAAD0RMvINAAAg");
	this.shape.setTransform(2812.775,-496.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(153,204,255,0.247)").s().p("EnkGB6JMAAAj0RMPINAAAMAAAD0Rg");
	this.shape_1.setTransform(2812.775,-496.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.rocket_mc}]}).wait(1));

	// foreground
	this.text = new cjs.Text("Rules for the Ducks:\n\n* Please be careful with the ducks, they tend to run in crowds or run faster than expected\n* Please dont feed the ducks outside food from what staff offers to you\n* Please don't try to take the ducks home... THAT IS STEALING\n* Pictures are allowed, just please be respectful  ", "bold 40px 'Arial'");
	this.text.textAlign = "center";
	this.text.lineHeight = 47;
	this.text.lineWidth = 743;
	this.text.parent = this;
	this.text.setTransform(4328.8,-1010.7);

	this.text_1 = new cjs.Text("Snacks:\nPizza: $4\nCheesecake: $4.50\nPretzal: $2.25\n* with cheese: $2.75\nNachos: $4.50\nIce cream: $1.25\nDonuts: $1.50", "bold 40px 'Arial'");
	this.text_1.textAlign = "center";
	this.text_1.lineHeight = 47;
	this.text_1.lineWidth = 400;
	this.text_1.parent = this;
	this.text_1.setTransform(3569.7,-1010.7);

	this.text_2 = new cjs.Text("Drinks:\nLemonade: $1.50\nLatte (hot/iced): $3.75\nMelon drink: $1.25\nFrappuccino: $3.99\nCappuccino: $2.99", "bold 40px 'Arial'");
	this.text_2.textAlign = "center";
	this.text_2.lineHeight = 47;
	this.text_2.lineWidth = 422;
	this.text_2.parent = this;
	this.text_2.setTransform(3134.85,-1026.8);

	this.text_3 = new cjs.Text("Guest Rules:\n* Please don't kick the ducks\n* Take off your shoes and put on the slippers staff give out", "bold 40px 'Arial'");
	this.text_3.textAlign = "center";
	this.text_3.lineHeight = 47;
	this.text_3.lineWidth = 306;
	this.text_3.parent = this;
	this.text_3.setTransform(1677.15,-697.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(4,1,1,3,true).p("ECWAApDMEsAAAAMAAAArVMksAAAAgECjThM4MB9eAAAMAAABatMh9eAAAgEiV/AlhIAAyJMEr/AAAIAAVrEAFDhN4MCIFAAAMAAABIlMiIFAAAgEietgT7IIuAAEjAegdgMAhxAAAIAAJlIAAT7IIuAAEjAeglEIAAHkEietAS5IIugBEietAAAIAAS5IAAKEMg49AAAIAAp+EmeNglEMgjyAAAMAAAgvTMEsAAAAMAAAAvTMgqfAAAMg4cAAAIAARJIcOAAIFCAAIAAplIXMAAEjarAAAIDBAAEjd9AS/IGTAAIAAy/IAAz7EjcsgT7ICBT7EjjwAlRIFDABMAgAAAHIgQKtMAo+AAAIAAqlEjjwAlRIAhK1IfkAAIEuAAEjxXAwGIOIAAEietAc9IAAIiIIuACEi+tAlZMAgAAAGEjd9AS/IgwSTEiV/BUYMgtsAAAMgtsAAAMg27AAAMg27AAAMgxZAAAMgxZAAAMAAAgkSIMmAAMAlDAAAMAlCAAAEiV/AwGMAAAAkSEjDrAwGMAAAAkSEjxXAwGMAAAAkSEj36AAAIggTCIadgDEkVJATFIcvgDEkVIAAAIdOAAIdPAAEkVpgT7IAhT7EkVpgT7IcvAAEkx3glEIggRJIcuAAEkyHAAAIAQTJIcugEIhASBILmACIiKK+IbWAAElOFATMIcOgDElPFAAAIc+AAIc/AAElQWgT7IBRT7ElQWgT7Id/AAEk78Ak+IAALIIT6AAIbVAAElNEAk6IRIAEMAlzAAIElOFATMIBBRuEj46glEMg49AAAMg9fAAAIBBRJId/AAElqzAAAIAgTPIcOgDEl5bATQIPIgBEmGBgT7IggT7IbuAAIbuAAEmGBgT7IXsAAEmeNglEIAgRJIXsAAEnB/gT7IKlAAIAAT7IYcAAIARTUMAlSgAEIAARgIOHADIAALTIMnAAMAixAAAEnB/AAAIKlAAEnB/ATYIYsgDIKmgBEm3agT7IZtAAEmRXAkrIBBLbMgAQAkSEnB/AkhIMWACIAQLjEm1pAkjIMWADIX8AFIX8AFElvWglEMgu3AAAEmpTATVIAARREme+AAAIYdAAElrUAkzIeQAHEkoCAwGMgAQAkSEletAwGMgAgAkSEkKjAlIMAmzAAJECWABUYMkr/AAA");
	this.shape_2.setTransform(2880,-540);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCCCFF").s().p("Eg+uAtXMAAAhatMB9eAAAMAAABatg");
	this.shape_3.setTransform(4326.6,-741.775);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("EhEBAkSMAAAhIjMCIDAAAMAAABIjg");
	this.shape_4.setTransform(3347.75,-806.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC9966").s().p("EiV/AggMAAAgkRIAAqlIAAyJMEr/AAAIAAVrMAAAArUg");
	this.shape_5.setTransform(2880,-208);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFCCCC").s().p("A8ddOIAAp+IAAy+IAAz7IAApkIXLAAMAhwAAAIAAJkIAAT7IAAS5IAAKDg");
	this.shape_6.setTransform(1681.975,-541.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#764B07").s().p("EBoUBUYMAAAgkSMAAAAkSMgtsAAAMAAAgkSIOIAAIfkAAIEuAAMAo+AAAMAAAAkSgEADtBUYMAAQgkSMgAQAkSMg26AAAMAAggkSMAiyAAAIT4AAIbWAAIbVAAMAAAAkSgEhkmBUYMAAQgkSMgAQAkSMgxZAAAMAAAgkSIMmAAMAlDAAAMAlDAAAIMmAAMgAgAkSgEA6oAwGgEgytAwGgEBrhglDMg4cAAAMg48AAAMg9fAAAMgu2AAAMgjzAAAMAAAgvUMEr/AAAMAAAAvUg");
	this.shape_7.setTransform(960,-540);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#999999").s().p("EiV/AVrMAAAgrVMEr/AAAMAAAArVg");
	this.shape_8.setTransform(4800,-138.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.text_3},{t:this.text_2},{t:this.text_1},{t:this.text}]}).wait(1));

	// placeholder
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CCCC99").s().p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	this.shape_9.setTransform(4800,-540);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#CC9966").s().p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	this.shape_10.setTransform(960,-540);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#CC9933").s().p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	this.shape_11.setTransform(2880,-540);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.background, new cjs.Rectangle(-287.5,-1279.8,6200.6,1567.4), null);


// stage content:
(lib.Holley_DuckCafeFinal = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,1];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		this.DoorHandle_mc.addEventListener("click",handleClickDoorHandle);
		function handleClickDoorHandle(event){
			root.play();
			var music_snd = createjs.Sound.play("music"); // music is the linkage name of the sound
		}
		
		document.addEventListener("keydown", handleKeyDown);
		document.addEventListener("keyup", handleKeyUp);
		
		var root = this;
		var speed = 50;
		
		function handleKeyDown(event) {
			console.log("background_.mc.x = " + root.background_mc.x);
			console.log(root.background_mc.x);
			if (root.duck_mc.currentFrame == 29){
				root.duck_mc.gotoAndPlay("walking");
			}
		
			if (event.keyCode == 39 && root.background_mc.x > -3540) {
				root.duck_mc.scaleX = 1;
				root.background_mc.x = root.background_mc.x - speed;
				
			}
		    if (event.keyCode == 37 && root.background_mc.x < 1310) {
				root.duck_mc.scaleX = -1;
				root.background_mc.x = root.background_mc.x + speed;
			}
		}
		
		function handleKeyUp(event) {
			root.duck_mc.gotoAndPlay("standing");
		}
		
		//this.background_mc.bird_mc.addEventListener("click",handleClickBird)
		this.bird_mc.addEventListener("click",handleClickBird);
		
		function handleClickBird(event){
			root.bird_mc.play();
			root.bird_mc.removeEventListener("click",handleClickBird);
			console.log("it should play in a loop")
		}
		
		this.background_mc.rocket_mc.addEventListener("click",handleClickRocket);
		
		function handleClickRocket(event){
			root.background_mc.rocket_mc.play();
			root.background_mc.rocket_mc.removeEventListener("click",handleClickRocket);
			console.log("it should play once")
			var BlastOff_snd = createjs.Sound.play("BlastOff"); // blast is the linkage name of the sound
		}
		
		
		this.background_mc.ball_mc.addEventListener("click",handleClickBall);
		
		function handleClickBall(event){
			root.background_mc.ball_mc.play();
			root.background_mc.ball_mc.removeEventListener("click",handleClickBall);
			console.log("it should play once")
			var knock_snd = createjs.Sound.play("knock"); // knock is the linkage name of the sound
		}
		
		this.background_mc.drink_mc.addEventListener("click",handleClickDrink);
		
		function handleClickDrink(event){
			root.background_mc.drink_mc.play();
			root.background_mc.drink_mc.removeEventListener("click",handleClickDrink);
			console.log("it should play once")
			var shake_snd = createjs.Sound.play("shake"); // shake is the linkage name of the sound
		}
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// walking
	this.duck_mc = new lib.walking();
	this.duck_mc.name = "duck_mc";
	this.duck_mc.setTransform(724.3,888.55,1,1,0,0,0,-112,131.8);
	this.duck_mc._off = true;

	this.timeline.addTween(cjs.Tween.get(this.duck_mc).wait(1).to({_off:false},0).wait(1));

	// birds
	this.bird_mc = new lib.birds();
	this.bird_mc.name = "bird_mc";
	this.bird_mc.setTransform(568.1,338.45,1,1,0,0,0,568.1,47);

	this.timeline.addTween(cjs.Tween.get(this.bird_mc).to({_off:true},1).wait(1));

	// buttons
	this.DoorHandle_mc = new lib.doorhandle();
	this.DoorHandle_mc.name = "DoorHandle_mc";
	this.DoorHandle_mc.setTransform(1089.8,831.4,1,1,0,0,0,-6.8,5.3);

	this.timeline.addTween(cjs.Tween.get(this.DoorHandle_mc).to({_off:true},1).wait(1));

	// text
	this.text = new cjs.Text("Open", "bold 75px 'Athelas'");
	this.text.textAlign = "center";
	this.text.lineHeight = 86;
	this.text.lineWidth = 262;
	this.text.parent = this;
	this.text.setTransform(947.45,599);

	this.text_1 = new cjs.Text("Welcome to the Duck Cafe", "bold 125px 'Athelas'");
	this.text_1.textAlign = "center";
	this.text_1.lineHeight = 142;
	this.text_1.lineWidth = 1163;
	this.text_1.parent = this;
	this.text_1.setTransform(952.1,24.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A3iu+MAvFAAAIAAd9MgvFAAAg");
	this.shape.setTransform(953.325,651.775);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC9999").s().p("A3iO/IAA99MAvFAAAIAAd9g");
	this.shape_1.setTransform(953.325,651.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.text_1},{t:this.text}]}).to({state:[]},1).wait(1));

	// Layer_1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(6,1,1).p("EgiFBUZMAAAhckMA+2AAAMAAABckMg+2AAAMh0MAAAMAAAioxMEsjAAAMAAACoxMh5hAAAEh9IABuIoxAAIIxqqMA6qAAAIAAKqMAAAAnnMg6qAAAMAAAgnnIAAqqEhCegI8IJiKqIpiAAMg6qAAAEBDPABVIAApIMAyfAAAIHzJIInzAAMAAAApWMgyfAAAMAAAgpWIpJAAIJJpIEB1ugHzIAAJIMgyfAAA");
	this.shape_2.setTransform(961.875,537.65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#666666").s().p("Eg+RAFWIAAqqIAAKqMg6rAAAIAAqqIAAKqIoxAAIIxqqMA6rAAAIJhKqgEB56AE9IAApIIAAJIMgyeAAAIAApIMAyeAAAIH0JIgEA+SAE9IJKpIIAAJIgEBHcgELg");
	this.shape_3.setTransform(935.025,514.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("EBG9AUrMAAAgpVMAyeAAAMAAAApVgEh5bATVMAAAgnmMA6rAAAMAAAAnmg");
	this.shape_4.setTransform(938.1,678.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#999999").s().p("EgfaAuSMAAAhcjMA+2AAAMAAABcjg");
	this.shape_5.setTransform(944.8,781.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#CCCCCC").s().p("EAcxBUYMAAAhcjMg+2AAAMAAABcjMh0MAAAMAAAiowMEsjAAAMAAACowgEA6GABVIJJAAMAAAApWMAyfAAAMAAAgpWIHzAAInzpIMgyfAAAgEiF5ABuIIxAAMAAAAnnMA6qAAAMAAAgnnIJiAAIpiqqMg6qAAAg");
	this.shape_6.setTransform(961.875,537.65);

	this.background_mc = new lib.background();
	this.background_mc.name = "background_mc";
	this.background_mc.setTransform(960,540,1,1,0,0,0,960,-540);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).to({state:[{t:this.background_mc}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(672.5,340.2,5240.6,1027.3999999999999);
// library properties:
lib.properties = {
	id: '9CB581EE8A6546A0B2CB83369DDC8DEF',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Holley_DuckCafeFinal_atlas_1.png?1779158431312", id:"Holley_DuckCafeFinal_atlas_1"},
		{src:"sounds/blast.mp3?1779158431330", id:"blast"},
		{src:"sounds/knock.mp3?1779158431330", id:"knock"},
		{src:"sounds/music.mp3?1779158431330", id:"music"},
		{src:"sounds/shake.mp3?1779158431330", id:"shake"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['9CB581EE8A6546A0B2CB83369DDC8DEF'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;